### ISSUE TITLE
Unable to save a runnable jar.

### ISSUE THREAD

**Issue by Chnkr** [Konloch/bytecode-viewer#101]
Trying to use the `save as runnable jar` function for a simple one-class `jar` results in the following error when using @samczsun his downstream fork. 

```
java.util.zip.ZipException: duplicate entry: Hello.class
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
    at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
    at the.bytecode.club.bytecodeviewer.JarUtils.saveAsJar(JarUtils.java:220)
    at the.bytecode.club.bytecodeviewer.gui.ExportJar$1$1.run(ExportJar.java:71)
```

The class itself contains the following code, it's just a simple hello world application.

```
class Hello
{
    public static void main(final String[] array) {
        System.out.println("Yes, this is a test.");
    }
}
```

I'm sorry for reporting downstream issues in this branch, but as i saw a open PR for some of the proposed changes, i'd felt it was easier to report them here, since issues seem to be turned off for forks?

**Comment by Konloch** [comment]
It works to report it here since I've just been pulling @samczsun's code anyways

**Comment by samczsun** [comment]
My bad. I've enabled issues should anyone want to report them downstream. You can consider my repo bleeding edge as I'm making some rather incompatible changes with the current BCV.

**Comment by Chnkr** [comment]
Cool! Will report issues downstream from now on.
