### ISSUE TITLE
Changing Krakatau assembler syntax

### ISSUE THREAD

**Issue by Storyyeller** [Konloch/bytecode-viewer#105]
Hi, I'm planning to change the Krakatau assembler syntax to simplify the grammar and make it possible to allow exact binary roundtripping. But this requires breaking backwards compatibility, so I figured I'd reach out here to see if you knew anyone using the assembler so I could try to discuss it beforehand.

As far as I can tell, most people just do disassemble/edit/assemble, so they won't be affected. It's only people who hand write assembly that will need to convert.

**Comment by Konloch** [comment]
Personally I just disassemble/assemble.

**Comment by Storyyeller** [comment]
The new assembler and diassembler is now available for you to try.

Notable changes:
* Full Java 8 support in assembler and disassembler (but not decompiler)
* Disassembler can now roundtrip to the exact binary of the original classfile
* Helpful and comprehensive error messages in assembler
* Assembler no longer requires Ply
* New assembler syntax
* Assembler syntax is now documented
* Fixed various bugs

**Comment by Storyyeller** [comment]
P.S. Would it be helpful if I use Github's Releases feature with Krakatau? This allows an easy zip download of specific versions, and creating a release might be easier than posting here to tell you to update. Assuming you have a way of being notified when I create a release for Krakatau.

**Comment by samczsun** [comment]
Hello,

I'm currently maintaining a bleeding edge version of Bytecode Viewer over at my fork.

The plan right now is to shade all the dependencies along with BCV, and so I'm manually downloading and incorporating Krakatau and Enjarify (to remove unneeded files like test files). It most likely won't make a difference whether you release via GitHub or I just download as zip.

I'll make another alpha release soon with the latest version of Krakatau

**Comment by Konloch** [comment]
If you could add them on the release site I could make it automatically fetch the latest Krakatau, same with Enjarify.

**Comment by Storyyeller** [comment]
On a side note, the Enjarify release zips already exclude test files, or at least they will as soon as I create a new release. I added an exclusion to gitattributes.

https://github.com/google/enjarify/blob/master/.gitattributes

**Comment by samczsun** [comment]
Oh, I see. I used to download as a ZIP from master. Now I do it from the latest commit to version it better

**Comment by Konloch** [comment]
Awesome, thanks for the information!
