### ISSUE TITLE
Downloadable zip detected as containing virus

### ISSUE THREAD

**Issue by sshikov** [Konloch/bytecode-viewer#106]
Virus Name: McAfeeGW: BehavesLike.Java.Suspicious.xm

**Comment by Konloch** [comment]
Which zip file?

**Comment by sshikov** [comment]
https://github.com/Konloch/bytecode-viewer/releases/download/v2.9.8/BytecodeViewer.2.9.8.zip

**Comment by Konloch** [comment]
Could be due to the jar to exe, oh well.

**Comment by Manouchehri** [comment]
https://www.virustotal.com/en/file/c5319c710f2ef51d58923b2ade31f933f47078ab6e31aa462023a82a7228f8eb/analysis/1450960702/
https://www.virustotal.com/en/url/c7b271a396a62a4dd72253365e8d2980182160ee601ae365775b806720baed5c/analysis/1450960696/

It's clean here.

**Comment by Konloch** [comment]
Interesting, I may switch back to the old jar2exe program I was using.

**Comment by Manouchehri** [comment]
It's only one antivirus (and not a great one either..). I'd just ignore it, not worth spending time on.

**Comment by Konloch** [comment]
Yeah you're right, until there's enough people wanting it to be changed I'll leave it for now.

**Comment by afffsdd** [comment]
if you are willing you can contact them and report a false positive. it generally takes about a day or two for them to fix

**Comment by Konloch** [comment]
Good point, I'll look into that options. Cheers!
