### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Radzhab** [Konloch/bytecode-viewer#108]
I try decompile apk file. Open any java class and try save without changes. Bytecodeviewer gives an  error message - " `package android.util does not exist"`. I try make `import android.util;` but still gives the same error. What i make wrong?
![image](https://cloud.githubusercontent.com/assets/2556411/11584683/d66533ca-9a76-11e5-94f8-4e9e9768e6c8.png)

**Comment by Radzhab** [comment]
this is apk file

**Comment by Radzhab** [comment]
http://rghost.ru/8c4QwxC9p this is apk file

**Comment by Radzhab** [comment]
How include libs in project?

**Comment by Righteous** [comment]
What are the exact steps you're trying to do? I'm having no problem decompiling the .apk, no errors on my side.

**Comment by Radzhab** [comment]
I want compile it) Compliling not work

**Comment by Radzhab** [comment]
https://youtu.be/WqEX48sKgtc i share screen video

**Comment by Radzhab** [comment]
please help me

**Comment by Konloch** [comment]
Java compiler is meant to compile Java, not decompiled Android classes that are then converted to Java.

Use a Bytecode Editor such as Smali or Krakatau for this.

**Comment by huckleberrypie** [comment]
Would it be golden if you integrate this with the Android SDK or something? That way it would save us the trouble of having to decipher what the decompiled bytecode does and instead work with the generated .java files.

I know that isn't without its risks considering how it can be used for piracy or worse, but some would like to do this for the sake of modding anyway.
