### ISSUE TITLE
rt.jar selection

### ISSUE THREAD

**Issue by theuserbl** [Konloch/bytecode-viewer#120]
Why do you ask for Krakatau for the rt.jar path?
The java.home property gives you the path automatically.

Same I have alreay ask the Helios author (Helios is a similar project like BytecodeViewer)
https://github.com/samczsun/Helios/issues/7
and he have fixed it
https://github.com/samczsun/Helios/commit/319c5c4e224a52357537c869bb061dcc5323cee0

**Comment by Konloch** [comment]
cheers
