### ISSUE TITLE
FileNotFoundException stacktrace while opening APK

### ISSUE THREAD

**Issue by rcchan** [Konloch/bytecode-viewer#123]
Start up took 14 seconds
I: Using Apktool 2.0.1 on velvet.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /usr/local/google/home/rcc/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values _/_ XMLs...
I: Copying raw classes.dex file...
I: Copying raw classes10.dex file...
I: Copying raw classes11.dex file...
I: Copying raw classes12.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying raw classes4.dex file...
I: Copying raw classes5.dex file...
I: Copying raw classes6.dex file...
I: Copying raw classes7.dex file...
I: Copying raw classes8.dex file...
I: Copying raw classes9.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
dex2jar /tmp/velvet.apk -> velvet-dex2jar.jar
java.io.FileNotFoundException: $HOME/.Bytecode-Viewer/bcv_temp/KAVLDWQKCTOXXjnKpoXvePLYe.jar (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at the.bytecode.club.bytecodeviewer.JarUtils.loadClasses(JarUtils.java:83)
    at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:878)

**Comment by Konloch** [comment]
Try using Enjarify for APK conversion, does it produce the same results?

**Comment by flowztul** [comment]
I'm experiencing the same issue, both with dex2jar and enjarify.
