### ISSUE TITLE
Update Krakatau

### ISSUE THREAD

**Issue by Storyyeller** [Konloch/bytecode-viewer#124]
Just a heads up, but I'm planning to push some improvements to Krakatau tomorrow.

Also, is there a better way to notify you of updates? If not, I can just post here whenever I update Krakatau.

**Comment by Storyyeller** [comment]
Update is now pushed

**Comment by Konloch** [comment]
I'll pull and update, cheers. Also I check konloch@gmail.com constantly so that might be better
