### ISSUE TITLE
Eternal loading - I can't compile any APK

### ISSUE THREAD

**Issue by LostJak** [Konloch/bytecode-viewer#126]
Hey guys.

First of all, thank you very much for your tool, Konloch. By the looks of it, seems like you've put a lot of work into this. Oh yeah, and nice avatar by the way, this movie is awesome =)

So, the thing is, I downloaded Bytecode Viewer so I could be able to do something that no other tool has ever made possible to me: reverse engineer an APK in a way that I am able to decompile it in java, **edit it in java**(not in smali) and **recompile it**. If Bytecode Viewer is not able to do this, you can stop me right here, as I probably misunderstood it's description.

But, if it's supposed to work like that, **my problem is:** Bytecode Viewer decompiles any APK in java just fine, and I am able to edit it too, after selecting "_Editable_" in _View --> Pane 1/2/3 --> JD-GUI_, but when I click on _File --> Compile_, an animated "loading" sign appears next to the _Plugins_ button, and it stays there forever.

No compilation, no new .apk generated, no error window. Nothing. Bytecode Viewer just stays there loading forever.

Is this a known error? Are you guys working on it to solve it or is it something that I'm doing wrong that I can easily avoid and just make the compilation goes alright?

Can you please help me out here? =/

![5248678](https://cloud.githubusercontent.com/assets/17623834/13509360/c4866d2e-e169-11e5-95ed-65dfc55871a8.png)

**Comment by Konloch** [comment]
Thank you! :D

This is a known bug, I've been meaning to look into this soon. It's
extremely experimental so most of the time decompiling the Java code to
recompile it will result in broken code anyways​ since it's rare to get a
100% full decompilation that matches 1:1 with what the source should be.

**Comment by Storyyeller** [comment]
In general, you shouldn't rely on being able to recompile code. Compilation and decompilation and conversion to/from dex are all lossy processes.
