### ISSUE TITLE
Krakatau v9 update broke 3.0.0 previews

### ISSUE THREAD

**Issue by SocraticBliss** [Konloch/bytecode-viewer#128]
Hey Konloch,

Just wanted to give you a heads up that the v9 update broke the 3.0.0 previews, as the preview jars are hard-coded to look for Krakatau v8, luckily I had an older backup of the Krakatau_8.zip, otherwise I would have been out of luck...

Fantastic tool by the way!

The smali to java re-compile via refresh is a godsend and killer feature :)

**Comment by Konloch** [comment]
Cheers! I've been meaning to fix this I've just been swamped with work
lately. Thanks for the report!
