### ISSUE TITLE
NullPointerException at BytecodeViewer$6.run when opening .apk

### ISSUE THREAD

**Issue by kzaikin** [Konloch/bytecode-viewer#132]
I run BV 2.9.8 at Ubuntu 15.10.
When I open an .apk I get the errors:

> Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: true
> 
> java.lang.NullPointerException
>   at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:868)

and another one

> java.lang.NullPointerException
>   at java.io.Writer.write(Writer.java:157)
>   at brut.a.d.c.b.a(Unknown Source)
>   at c.d.a.a.a(Unknown Source)
>   at c.d.b.a.a.d.a(Unknown Source)
>   at c.d.b.a.a.b.b(Unknown Source)
>   at c.d.b.a.a.b.a(Unknown Source)
>   at brut.a.d.b.p.a(Unknown Source)
>   at brut.a.d.b.o.a(Unknown Source)
>   at brut.a.d.b.o.b(Unknown Source)
>   at brut.a.d.b.j.a(Unknown Source)
>   at brut.a.d.a.b(Unknown Source)
>   at brut.a.a.c(Unknown Source)
>   at brut.a.c.a(Unknown Source)
>   at brut.apktool.Main.a(Unknown Source)
>   at brut.apktool.Main.main(Unknown Source)
>   at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
>   at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:864)

I have tried dex2jar and enjarify for apk conversion. Errors are the same

**Comment by kzaikin** [comment]
Apk is opened OK when I disable resource decode
I was able to find it out when I saw the following error output

> I: Loading resource table from file: /home/kzaikin/apktool/framework/1.apk
> W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000013
> java.lang.NullPointerException

**Comment by moelfassi** [comment]
same here

**Comment by Janmm14** [comment]
@moelfassi @kzaikin Latest version tried using the Bootstrapper to launch?

**Comment by einmalfel** [comment]
+1

**Comment by btwarog** [comment]
+1

**Comment by m-ajitabh** [comment]
+1

**Comment by Konloch** [comment]
This should be fixed in the latest version, thanks for the reports!
