### ISSUE TITLE
A Java Exception has occured

### ISSUE THREAD

**Issue by Drjacky** [Konloch/bytecode-viewer#134]
I got this error, after running BytecodeViewer.exe, or double click on a APK (after installing BytecodeViewer with _install BCV.bat file) :

Java Virtual Machine Launcher
A Java Exception has occured

**Comment by Janmm14** [comment]
Try launching through console to get the error message.

**Comment by Drjacky** [comment]
When running exe file through console, I just get said error, but when running jar, I got this:

**Comment by walidsa3d** [comment]
I got the same error, then the GUI doesn' show decompiled classes (blank pane).

**Comment by liujunhg** [comment]
I got the same error too

**Comment by savior14** [comment]
after years of having the same error, this is still not yet fixed. maybe the project is already discontinued. no replies also or whatsoever.

**Comment by Konloch** [comment]
This bug should be fixed in the latest version, if you're still experiencing this bug please open a new issue on GitHub or E-Mail me directly and I'll solve it.
