### ISSUE TITLE
can't find brut/apktool/Main?

### ISSUE THREAD

**Issue by kenyee** [Konloch/bytecode-viewer#135]
When running the viewer.exe, it doesn't do anything when I drag/drop APKs onto it (same thing if I do Add)...wish there were a way to dump debug logs somewhere so we can look at them :-(

So I tried running:

> BytecodeViewer -i my.apk -o output.zip -t all

and I get the cryptic stack trace below:

> Exception in thread "Thread-9" java.lang.NoClassDefFoundError: brut/apktool/Main
>         at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
>         at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:864)
> Caused by: java.lang.ClassNotFoundException: brut.apktool.Main
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)

I'm using 2.9.8 of BCV...latest Android SDK is loaded.  Java version is 1.8.0_72

**Comment by shengbeiniao** [comment]
Some problem,no idea...

use mac,run java -jar

**Comment by alexanderkunz** [comment]
Confirmed problem...

**Comment by lambasoft** [comment]
Having the same issue, any solutions ?

**Comment by autovalue** [comment]
Having the same issue @Konloch. Potentially outdated libraries being downloaded?

**Comment by Konloch** [comment]
This should be fixed in the latest version, thanks for the reports!
