### ISSUE TITLE
Make tabs rearrangeable

### ISSUE THREAD

**Issue by 0xdevalias** [Konloch/bytecode-viewer#139]
It would be awesome if we could rearrange the tabs when we have multiple files open. (Similar to how chrome does it)
- Drag tabs to change the order.
- Drag a tab 'out of' the tab bar to have it open in a new window.
- Etc

**Comment by weisJ** [comment]
Darklaf does support this behaviour when enabling drag and drop for tabbed panes:

https://github.com/weisJ/darklaf/blob/54bd006ad249dc98bd11b977532b99c7aad2ffca/core/src/test/java/com/github/weisj/darklaf/ui/tabbedPane/AbstractTabbedPaneDemo.java#L107

(Only the `putClientProperty` part is relevant)

**Comment by Konloch** [comment]
A preview for this feature is located at https://github.com/Konloch/bytecode-viewer/actions/runs/7245057185 - it will be included in the next BCV release
