### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by Manouchehri** [Konloch/bytecode-viewer#146]
The little indicator doesn't show how many files are left to decompile when exporting all; it would be nice if there was some more feedback to the user to let them know the progress.

![image](https://cloud.githubusercontent.com/assets/7232674/16442355/f9bfeb90-3d9f-11e6-8717-a1c6a008ba74.png)

**Comment by IAmWolfie** [comment]
I agree. Sometimes this will get stuck for me, and I don't know what to do. A fix/improvement of this would be fantastic!

**Comment by Konloch** [comment]
I've done my best to tackle this in v2.9.16, it could still be way better but I think this will work for the 2.9x branch, thanks for the suggestion!
