### ISSUE TITLE
Finding all references to a field/method/etc.

### ISSUE THREAD

**Issue by anonpenguin** [Konloch/bytecode-viewer#147]
Hi, thanks for the great product. :) Just curious, is it possible to find all references to a given field/method/etc? I'm decompiling a fairly large application and it's kind of hard to know exactly where the methods I'm looking at are being used, so it'd be useful to have this feature.

Thanks for helping!

**Comment by Janmm14** [comment]
The search box in the lower left corner should do the trick.

**Comment by sh1ftchg** [comment]
Note: It doesn't find all references. Fun fact - polymorphism, inheritance, reflection, and instrumentation make it impossible to actually detect all references. You can even do tricky things like reference a static member from a different location in the hierarchy. See "linking" in the JVM specifications for more details.
