### ISSUE TITLE
Moving Enjarify to Rust

### ISSUE THREAD

**Issue by Storyyeller** [Konloch/bytecode-viewer#150]
Hi, I am considering changing Enjarify from Python to Rust, which would require compiling a static binary. Do you think this is something you could handle? It makes distribution a lot more annoying but it also brings increased performance.

**Comment by Konloch** [comment]
Hey there, thanks for checking :D. And no it shouldn't be too hard to
implement on my end, it should be possible in the current system without
too many major changes.
