### ISSUE TITLE
Opening classes with same names from separate .jars causes problems

### ISSUE THREAD

**Issue by korri123** [Konloch/bytecode-viewer#163]
Say I have two OSRS gamepacks, gamepack131.jar and gamepack132.jar. I add them both to my workspace, but bytecode viewer only loads the classes of the other jar, no matter what, because all the files are named the same.

**Comment by jowasp** [comment]
which version are u using?

**Comment by korri123** [comment]
The latest compiled version in the releases section, but I'm using a fork now that fixed the issue, JDA: https://github.com/LLVM-but-worse/jda

**Comment by Konloch** [comment]
Thank you for this report, it will be fixed in v2.9.16.
