### ISSUE TITLE
FernFlower decompiler shows wrong label

### ISSUE THREAD

**Issue by Venryx** [Konloch/bytecode-viewer#165]
The FernFlower decompiler shows up as "CFR Decompiler" (right most in this picture): ![](http://i.imgur.com/KoLXq03.png)

**Comment by jowasp** [comment]
Would it be possible you provide the apk you used so we can test that?

**Comment by Janmm14** [comment]
It does not just happen with apks, it happens for everything

**Comment by Venryx** [comment]
Yeah, it happens for everything, so doesn't need any specific apk uploaded. (probably just a typo in a class constant somewhere)
