### ISSUE TITLE
Not Compiling

### ISSUE THREAD

**Issue by winkerbie** [Konloch/bytecode-viewer#169]
I cant seem to compile my edited program.jar file

I have loaded up the .jar file in ByteCode Viewer v2.89. I only use one pane which is set to the "JD-GUI + Editable", no other panes open. 

Then I "Add" the .jar file I wish to edit, find the class and modify a static string the code

When I select "save as runnable jar file" nothing happens. There are moving bars on the top tool bar but nothing else happens. I don't have an output/error log either

Am I doing something wrong or is this a bug?

Using Win 10 x64, with the variables pointing at the x64 version of the Java JDK

**Comment by kuqn** [comment]
same

**Comment by stubull05** [comment]
same

**Comment by Bawabawa01** [comment]
Same

**Comment by Konloch** [comment]
Thanks for the reports! This will be fixed in v2.9.16.
