### ISSUE TITLE
Editor no save

### ISSUE THREAD

**Issue by dollarssign** [Konloch/bytecode-viewer#177]
Hi, when i edit some thing in the class, after i click "save as" i save the update on the desktop but the url that i change never changed

**Comment by ItzSomebody** [comment]
Well what editor are you using?

**Comment by helloxdd** [comment]
already fixed, thanks

but i think you know how to use bytecodeviewer better, how to add a library? for example spigot , because when compiler you need to insert the library

**Comment by ItzSomebody** [comment]
Just drop it a Spigot jar or PaperSpigot jar into the Files area where you drop the files you are decompiling

**Comment by helloxdd** [comment]
the compiler is very slow

**Comment by ItzSomebody** [comment]
Well, ByteCode Viewer was meant for ByteCode reverse-engineering :D
