### ISSUE TITLE
Build fails due to latest commit. error: non-static variable this cannot be referenced from a static context

### ISSUE THREAD

**Issue by Mydayyy** [Konloch/bytecode-viewer#182]
Hi all,

due to the latest commit, the build no longer works. The error is:

> error: non-static variable this cannot be referenced from a static context

The problem was introduced by the following commit: https://github.com/Konloch/bytecode-viewer/pull/181/commits/54488b1cfc15f900aafe40ecd6ae649b3b47a183

The error resides in line 155 here: https://github.com/Konloch/bytecode-viewer/blob/54488b1cfc15f900aafe40ecd6ae649b3b47a183/src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java#L155

I am not sure what exactly the goal of that line is, as I am not that familiar with java, otherwise I would have created a pull request.

~Mydayyy

**Comment by Konloch** [comment]
Sorry about that! I never verified the pull request. I've reverted the change back to it's original code.

Thanks for the report!

**Comment by ankemp** [comment]
Why am I getting notifications from this project? This started a few days ago, and I've never subscribed or even heard of it before.

**Comment by webdevbrian** [comment]
Same here @ankemp ...
