### ISSUE TITLE
Don't use 'Revert' Pull Requests

### ISSUE THREAD

**Issue by FFY00** [Konloch/bytecode-viewer#185]
Use, `git reset` instead. This will remove the last commit (change 1 to the numbers of commits you want to remove).
```git reset HEAD^1```

**Comment by lockie** [comment]
God damnit, why i keep receiving notifications about this repository I'm not even remotely interested in? Is @homakov pentesing github again?

**Comment by dantheflyingman** [comment]
They Dun Diddaly Broke It!

**Comment by MazeWebArchitect** [comment]
Second here. I'm receiving notifications about this repository without an subscription -.-

**Comment by jangrewe** [comment]
Guys, please have a look here: https://github.com/Konloch/bytecode-viewer/issues/184

**Comment by mark1145** [comment]
Quit your whinging!

On 9 Jan 2018, at 10:56, dantheflyingman <notifications@github.com<mailto:notifications@github.com>> wrote:

They Dun Diddaly Broke It!

**Comment by aleksandrkbl** [comment]
--
Отправлено из Mail.Ru для Android вторник, 09 января 2018г., 15:59 +05:00 от mark1145  notifications@github.com :

>Quit your whinging!
>

**Comment by aleksandrkbl** [comment]
--
Отправлено из Mail.Ru для Android вторник, 09 января 2018г., 15:59 +05:00 от Jan Grewe  notifications@github.com :

**Comment by aleksandrkbl** [comment]
--
Отправлено из Mail.Ru для Android вторник, 09 января 2018г., 15:58 +05:00 от MazeWebArchitect  notifications@github.com :

**Comment by jangrewe** [comment]
@aleksandrkbl you're not helping. read #184

**Comment by ehidle** [comment]
I went in an "unstarred" it yesterday (even though I never "starred" it in
the first place"... and all was quiet.. and then I started getting these
emails again... checked the project page and now I am spuriously "watching"
it... so now I "unwatched" it..

Something is wrong with github for sure that it's randomly adding watchers
and stars to projects.

*--*
*"Whatever is true, whatever is honorable, whatever is just, whatever is
pure, whatever is lovely, whatever is commendable, if there is any
excellence, if there is anything worthy of praise, think about these
things." -- Philippians 4:8*

**Comment by Andrew82788** [comment]
Enough, I get that it isn't your fault. I am tired of being grouped into
this email. I understand that a bunch of people were added without reason,
a glitch. Remove me. thanks
