### ISSUE TITLE
Some nice features

### ISSUE THREAD

**Issue by samczsun** [Konloch/bytecode-viewer#19]
Ctrl-O to open a file, Ctrl-N for a fresh workspace, or even custom keybinds for actions

Maybe store a file inside %appdata% (or the UNIX equivalent) to reference the last browsed folder in 'Add', so when someone opens it again, it'll default to that folder?

**Comment by Konloch** [comment]
I'll work on adding these, thanks for the suggestions!

**Comment by Konloch** [comment]
Confirmed added into 2.7.0.
