### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by riglerkarve** [Konloch/bytecode-viewer#193]
![screenshot 2018-03-24 13 43 36](https://user-images.githubusercontent.com/37740687/37864610-692f1750-2f69-11e8-8dda-a827290e7b23.png)
Hi,

I have just downloaded this today and it keeps saying the files downloaded are corrupted and to restart.

after every restart, the same messages appear (multiple items are corrupted) 

It starts with the following screenshot.

Using version 2.9.10

**Comment by Konloch** [comment]
Could you try running it via command line as java -jar bytecode-viewer-2.9.10.jar -clean

This should clean the directory, if this still persists try deleting C:/users/<username>/.Bytecode-Viewer (it's a hidden file so you might need to change your explorer settings)

If that still fails let me know. I've got a bit of time this weekend so I'm going to try to solve all of BCV's booting issues.

Cheers and thanks for the report!

**Comment by riglerkarve** [comment]
I've tried both of those issues, with no luck :(

![screenshot 2018-03-24 20 54 59](https://user-images.githubusercontent.com/37740687/37868858-aa319dea-2fa5-11e8-9c24-d6f32805e7e8.png)

Full error log from command prompt here: 
https://pastebin.com/DQduypik
![screenshot 2018-03-24 20 54 59](https://user-images.githubusercontent.com/37740687/37868889-1668329e-2fa6-11e8-8016-8f461279dc6a.png)

**Comment by Konloch** [comment]
Cheers, that error log should help me track this bug down.

It seems like downloading works, but loading the jars is failing.

To confirm this, could you compare the file size of the jars in your C:/users/(username)/.Bytecode-Viewer/libs/ with the files in https://github.com/Konloch/bytecode-viewer/tree/master/libs

They should be the same size if the downloader is working.

Also, could you type 'java -version' and send me your Java version? That might help track down this issue a bit more

**Comment by riglerkarve** [comment]
C:\Users\Jon>java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

For the libs that successfullly installed, they are the same size as in the lib folder on here.

**Comment by Konloch** [comment]
Java 10 might be bugged, I'm still working on getting Java 9 working.

I think I might've found where it's erroring out, are there any libraries that didn't install/download? if so that might explain the issue.

[Bytecode-Viewer-2.9.11-temp-dir-fixed.jar.zip](https://github.com/Konloch/bytecode-viewer/files/1844805/Bytecode-Viewer-2.9.11-temp-dir-fixed.jar.zip)

In this version I changed the bootloader to ensure the /temp/ directory exists, and if it doesn't force create it before it unzips to that folder.

If you can please try this version and let me know if this error is still persisting

**Comment by riglerkarve** [comment]
As is - I can now see the temp folder being created, however, same errors appear. I am now downloading java 8 to see if that will make  difference

**Comment by riglerkarve** [comment]
Changing to Java 1.8 worked

C:\Users\Jon>java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by Konloch** [comment]
Awesome, I'm glad 1.8 is a fix for now. I'll try to get JRE 9 and 10 working by this weekend.

If anyone has a working JDK 9 Classloader let me know, if not I'll just built a 'FatJar' version of BCV and that should support JRE 9 and then hopefully JRE 10.

Thanks for the update and trying out the patch.

**Comment by riglerkarve** [comment]
No problem, glad to to my part in improving this awesome set of tools
