### ISSUE TITLE
apktool is too old version

### ISSUE THREAD

**Issue by etmatrix** [Konloch/bytecode-viewer#199]
There are many issues ( #141 #162 #180 #167 #166 ) on this repository which has problems with apk decompile, the cause is always the same: apktool's version is too old 2.0 and now there is 2.3.2.
Old version of apktool give me many nullpointer but the version 2.3 is stable and works very well.
I resolved the issue with unpack fat jar of bytecodeviewer and replace all classes, properties and jar from apktool.jar excluded org.apache.common.*, I packed the new directory and now ByteCodeViewer has apktool 2.3 and works on many apk.
I known is not good way for resolve the issue, but this repository don't include project's file, so is not easy build a new version. I hope @Konloch can improve it.

**Comment by cjk** [comment]
Hope the current maintainer takes note.

**Comment by aliveli49** [comment]
@etmatrix can you share your updated jar? Or can you share step by step how to update bytecodeviewer jar?

Thanks

**Comment by cs16lover** [comment]
@Konloch  Why are you deleting comments?

**Comment by cs16lover** [comment]
@etmatrix could you please send updated jar? Or tell  exact steps to create updated jar?
@Konloch  is deleting the comments.

**Comment by Konloch** [comment]
@etmatrix thanks for this report. To everyone else using this as a discussion platform this is not what I would like the issue section to be used for, I'd like it to only be issues with BCV and not spam regarding updates around it.

**Comment by Konloch** [comment]
applied these changes in https://github.com/Konloch/bytecode-viewer/releases/tag/v2.9.14, thanks again @etmatrix.
