### ISSUE TITLE
NullPointerException when single class decompilation

### ISSUE THREAD

**Issue by AlanSandovalDev** [Konloch/bytecode-viewer#206]
Hello!
First, thanks for this app... is very useful.

The issue that I'm having is when I try to decompile a single class. For example, I open a class and then I select the option "File" > "Decompile & Save Opened Class...". I select the location and a window is prompted to choose a decompiler. For each decompiler an exception is thrown and the file is not saved.
Let me know if you need more information.
Thanks!

![2018-07-06 10_33_33-bytecode viewer 2 9 11 - stack trace - send this to konloch - konloch gmail com](https://user-images.githubusercontent.com/38866667/42384495-2139e042-8108-11e8-8b83-07a164531ce6.png)

**Comment by olbb** [comment]
Same issue here, please suggest a fix.

**Comment by Konloch** [comment]
Thanks for the bug report! This will be fixed in v2.9.16.
