### ISSUE TITLE
Loading forever..

### ISSUE THREAD

**Issue by GthisguyG** [Konloch/bytecode-viewer#207]
Loading forever..
_____________________

I set the javac executable as ask (program was asking or saying error everytime).

And now its loading forever if i turn on editable and try to refresh or savind, decompile etc.

Bugs out with every pane.

Please help thanks!

Version: 2.9.11

Where Javac is stored in: jdk1.8.0_101 folder.

**Comment by Konloch** [comment]
Thanks for the report! This will be fixed in v2.9.16.
