### ISSUE TITLE
FernFlower Signatures of feilds missing

### ISSUE THREAD

**Issue by jredfox** [Konloch/bytecode-viewer#212]
Issue: the signature of the fields appear to be missing example: `IntHashMap<Entity> becomes IntHashMap`

Steps to reproduce:
decmopile mc World.class such as from forge after you compile it using eclispe or get the already compiled class from the mc 1.12.2 jar after looking up its notch class name
make sure you select fernflower

**Comment by Konloch** [comment]
I've updated the fernflower library, hopefully this will fix the bug. If it doesn't just comment here or open up a new issue.

**Comment by jredfox** [comment]
Issue persists on the latest version. Using prycon fixes the signatures but, that decompiler library messes with code and I prefer fernflower please fix it.

**Comment by Konloch** [comment]
Darn, thanks for testing it!
