### ISSUE TITLE
Compile JSP error

### ISSUE THREAD

**Issue by cn-core** [Konloch/bytecode-viewer#217]
BytecodeViewer can edit JSP compiled after classes.....?
[](http://idataway-oa.oss-cn-beijing.aliyuncs.com/common%2F20181124164632.png?OSSAccessKeyId=ZfrcUg62TV8AWHc0&Expires=1543483430&Signature=2%2ByV6De%2FWZNPrbDK%2FbIqVitD8X0%3D)

**Comment by Konloch** [comment]
If anyone can E-Mail me an example JSP file I can look into adding support for it.

Konloch@gmail.com

**Comment by Konloch** [comment]
WAR/JSP decompiling will be in BCV 2.9.18
