### ISSUE TITLE
Can you help me recover the source code of xray ?

### ISSUE THREAD

**Issue by NullHF** [Konloch/bytecode-viewer#219]
For almost 2 years, xray is no longer maintained by the owners
So, I try to maintain myself but I get too much error to get class in .java

Original : 
*

Renamed :
*

I succes (i think) totally renamed version (class name) works well, but after decompilation and backup it does not work anymore, and it lacks a lot of code
I can only edit the code as a string via Smali / Dex
I'd like so much to get the clean code to edit it in eclipse easily
Thank you if anyone can help me

**Comment by voltagex** [comment]
This is not the right place to ask this.
