### ISSUE TITLE
Issue #202 repeats for windows

### ISSUE THREAD

**Issue by GSharma789** [Konloch/bytecode-viewer#220]
Hope title is enough. Please fix the krakatau. Thanks

**Comment by GSharma789** [comment]
hi dev , you closed the issue but i am still facing same issue in 2.9.13

**Comment by Konloch** [comment]
I'm unable to replicate it on my end @GSharma789, please open a new issue including as much information as possible. (or just reply here, that also works)

BCV currently requires an internet connection on first boot, so make sure you have internet access. For v2.9.16 I'll look into dropping the remote downloader and replacing the fat-jar loader.

**Comment by Konloch** [comment]
I've disabled the remote loader for v2.9.16, this should fix the issue. If it's not fixed in v2.9.16 please open a new issue or E-Mail me at Konloch@gmail.com and I'll get it sorted for you.
