### ISSUE TITLE
Two different classes with same name / .class file in BCV root folder

### ISSUE THREAD

**Issue by VADemon** [Konloch/bytecode-viewer#221]
This issue relates to #163 and #201 - they deal with one class name across different namespaces.

**BCV picks the wrong class file for decompilation when a file with this name is present in the BCV folder.**

Here, I noticed when I try to view OR decompile, say `abc.class` from `Some.jar` while `abc.class` is present in the folder where BCV jar is then:

1) When I open the preview of abc.class from the jar: the correct Some.jar>abc.class is shown

2) When I try to decompile the WHOLE jar, then every class file is decompiled correctly except for the abc.class, not the one inside the .jar file is used, but the actual file that is inside BCV folder. (harddisk>abc.class)

But when I renamed the `abc.class` on my hard drive - the decompilation proceeded correctly and extracted the right file from the jar.

**Comment by Konloch** [comment]
Thank you for this report, it will be fixed in v2.9.16.
