### ISSUE TITLE
CFR issue in BCV

### ISSUE THREAD

**Issue by GSharma789** [Konloch/bytecode-viewer#223]
Hi dev , i am facing error with cfr decompiler , if any apk contain classes name like con , lpt1, aux etc , than decompiler not work .

**Comment by Konloch** [comment]
would you happen to have an example class/jar file so I could test this out?

**Comment by GSharma789** [comment]
Please have a look at this  https://github.com/java-deobfuscator/deobfuscator/issues/216    .There are dexguarded apk and dex , please try and test some of con or aux classes  with cfr , i tried them in 2.9.12 , not sure with latest version . Thanks
