### ISSUE TITLE
[2.9.19] Infinite loading.. trying to load in android classes.dex

### ISSUE THREAD

**Issue by fOmey** [Konloch/bytecode-viewer#230]
Using version 2.9.11 seems to load them up just fine..

[apk.zip](https://github.com/Konloch/bytecode-viewer/files/3147246/apk.zip)

**Comment by Konloch** [comment]
Could you tell me which operating system you're running 2.9.19 on? Cheers!

**Comment by fOmey** [comment]
Windows 10, 64bit.

**Comment by Konloch** [comment]
This seems to be fixed now, both Enjarify and Dex2Jar can process this file using the latest version
