### ISSUE TITLE
A file with the same name in a jar is overlapped

### ISSUE THREAD

**Issue by hheg** [Konloch/bytecode-viewer#235]
If I view a MANIFEST.MF in one jar and then views the same MANIFEST.MF file in another jar, Bytecode-viewer shows the content of the first MANIFEST.MF file in the second MANIFEST.MF file window. They do not contain the same information if the jar is unpacked separately. I think that other resources are being treated the same way, and is obvious when comparing jars. This is BCV 2.9.18

**Comment by sh1ftchg** [comment]
Looked at it, seems it's how the viewers are managed - stored in a Map instead of a List; the task of opening one first checks the Map for existence very simply.

**Comment by sh1ftchg** [comment]
Solution is to use unique identifier, at least in its current form. 

Currently uses `container.name > file.name` as the keys however container names may not be unique.

It should use a facsimile of unique identifiers - not unlike a complete URI: `"file://share/drive/location.jar!/some/silly/code/example.class"`

I'm too lazy to fork clone MR this though.
