### ISSUE TITLE
Exact navigate to class

### ISSUE THREAD

**Issue by lurumdare** [Konloch/bytecode-viewer#239]
How to quick navigate to class?

a>a>a.class
a/a/a.class
b.b.b.class

Thanks.

**Comment by Konloch** [comment]
You should be able to navigate using the quick file search

![](https://i.imgur.com/dJZmZ3p.png)

To search with it, use the fully qualified name formatted as `b.b.b.class` (you can also search without the `.class` but if it has any subclasses those will be opened as well)

I'll look into adding the formats you mentioned!

**Comment by lurumdare** [comment]
Thanks. Worked.
