### ISSUE TITLE
Try to modify smali and run&compile 

### ISSUE THREAD

**Issue by b03201003** [Konloch/bytecode-viewer#242]
Hi, I'm trying the bytecode.club.crackme level 1 test, and I'm wondering how can I modify the smali code and rebuild in BCV. 
But when I try to recompile it (File->Compile)before any edit, I got "Keep in mind most decompilers cannot produce compilable classes":  
![image](https://user-images.githubusercontent.com/20508133/59497238-a2a5ff00-8ec5-11e9-85c1-e5ccdd3561ae.png)
Isn't it supported to edit the smali in BCV and rebuild? Maybe I don't know how to use these functions.

Also, the main function of level 1 has an argument "String[] a". How can I run this program in BCV with an argument? It is always failed if I just select File->Run .
![image](https://user-images.githubusercontent.com/20508133/59497587-54ddc680-8ec6-11e9-9617-876607128ab7.png)

Just a beginner of JAVA reversing. Thanks for any help!!

**Comment by Konloch** [comment]
Hey, BCV has a Java compiler built in as well, you've got that setting enabled so it's trying to use the Java compiler, as well as the Smali compiler. 

To disable the Java compiler it should be under View>Pane>CFR>Editable then make sure it's not toggled.

The smali compiler is designed for APK reversing, it most likely won't work with Java classes (some might work but the majority wont).

The EZ-Injection plugin is most likely broken, I'll look into that and fix it for the next update, thanks for letting me know about that.

If you've got any more questions feel free to E-Mail me at konloch@gmail.com
