### ISSUE TITLE
Directory Issue

### ISSUE THREAD

**Issue by apkunpacker** [Konloch/bytecode-viewer#244]
Error : step to reproduce --step 1 : create any new folder anywhere in disk , i created c:\new folder  . Step 2: put any jar , apk or any supported file inside new folder . Step 3 : press ctrl+n to open file and select that new folder , instead of opening that folder bcv imported whole folder and opening that jar from imported folder result into only hex view of jar . NOTE : after performing above step if we perform same step 3 again with add option ( not with ctrl+n) now bcv open that folder instead of importing into . So error is only on every first time opening . Hope dev you can reproduce it . Windows 7 x64 ,jre1.8.0_192, jdk-11.0.1 . Thanks

**Comment by Konloch** [comment]
This should be resolved in the latest build, thank you for the report
