### ISSUE TITLE
Add classpath for Krakatau

### ISSUE THREAD

**Issue by samczsun** [Konloch/bytecode-viewer#25]
It'd be a nice addition, otherwise the one decompiler that works the best is really limited.

Also, what do you mean by that "Obfuscator" ticket? Write an obfuscator or add something to deobfuscate?

**Comment by Konloch** [comment]
Theres an unfinished obfuscator in BCV, I haven't had any luck with it so I've given up for now.

I'll add Krakatau Classpath soon, thanks for the input!

**Comment by Konloch** [comment]
Added in 2.9.4, thanks again for the suggestion!
