### ISSUE TITLE
Respect the XDG basedir specification

### ISSUE THREAD

**Issue by piegamesde** [Konloch/bytecode-viewer#250]
I just installed your tool and now found a big ugly `.Bytecode-Viewer` in my home directory. Please respect the [XDG basedir specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead.

**Comment by lhanson** [comment]
Seconded, please don't spew things in my `$HOME`.

**Comment by alsoGAMER** [comment]
hello, any updates on this?
