### ISSUE TITLE
File handle leak

### ISSUE THREAD

**Issue by Vampire** [Konloch/bytecode-viewer#251]
I had a class open in Bytecode Viewer with Bytecode and Procyon views open.
This locked the files on disk on Windows which made it unable to recompile those files.
So there is somewhere a file handle leak that is not properly closed.

**Comment by Konloch** [comment]
This should be fixed for the next release with https://github.com/Konloch/bytecode-viewer/commit/aea66fea92aa07a592253531662c770fe2708069 - You can test this out by using the latest BCV binary from our [snapshot artifacts](https://github.com/Konloch/bytecode-viewer/actions/runs/11099163271).

If you're still experiencing this issue, please open a new issue and let us know
