### ISSUE TITLE
Not new compiled jar saved

### ISSUE THREAD

**Issue by peterpan444** [Konloch/bytecode-viewer#252]
Hi, I opend a Jar, made few changes and pressed on "Compile". The Compiler says that the compiling is done. Then I pressed "Save as jar" and saved the file. 

Now I opened the saved Jar into JD-GUI for checking the Class I've made the changes and as I see, no changes effort.

Any Ideas why my code changes are not saved / compiled into that new JAR?

**Comment by brusarp** [comment]
Me too... same error

**Comment by Honorable1337** [comment]
lmao same error after 2 years

**Comment by Konloch** [comment]
> lmao same error after 2 years

it should be fixed in v2.10.13. If you're encountering issues with it still Java editing isn't fully supported just because the decompiler won't be able to get the source fully

Try using Krakatau Disassembler with the edit option, or Smali if you're editing an android APK
