### ISSUE TITLE
 is there something wrong with bytecodeview wiki?

### ISSUE THREAD

**Issue by generalbao** [Konloch/bytecode-viewer#256]
https://wiki.bytecode.club/BCV

**Comment by generalbao** [comment]
**php miss extension**

MediaWiki 1.27 internal error
Installing some PHP extensions is required.

Required components
You are missing a required extension to PHP that MediaWiki requires to run. Please install:

mbstring (more information)
xml (more information)

**Comment by Konloch** [comment]
Hi thanks for this report, I've got the wiki back online.

**Comment by generalbao** [comment]
thankyou very much
