### ISSUE TITLE
unable to open apks possibly due to outdated dex2jar tool

### ISSUE THREAD

**Issue by Lanchon** [Konloch/bytecode-viewer#27]
there is a bug in dex2jar 0.9.15 that prevents reversing apks created with smali 2. the dex2jar 0.9 branch is abandoned and the 2.x branch does not have this bug. there is dex2jar 2.0 and 2.1 snapshots too.

because the release of your tool is obfuscated (!!!) i cannot check the version of dex2jar you are using, but it looks like you are using the old 0.9.15.

please see details here:
https://sourceforge.net/p/dex2jar/tickets/235/

**Comment by Konloch** [comment]
Thank you for this! I'll fix this issue in 2.9.3, I've also got to update CFR decompiler's library.

Keep these bug reports coming! :D

**Comment by Konloch** [comment]
I've updated dex2jar to 2.0 in 2.9.3, expect it to come out very shortly.

**Comment by Lanchon** [comment]
thank you!!

**Comment by Konloch** [comment]
2.9.3 is out, if you can please verify that this is fixed that would be great.

**Comment by Lanchon** [comment]
now it works, thanks! :)
