### ISSUE TITLE
Apk made Bytecode crash

### ISSUE THREAD

**Issue by lucafont2** [Konloch/bytecode-viewer#274]
When i try to open an apk on bytecode it crashes and leave me a file on desktop. This happen only with large apks
![image](https://user-images.githubusercontent.com/62725689/82760965-667a5e80-9df7-11ea-8208-a321c7e517ef.png)

![image](https://user-images.githubusercontent.com/62725689/82760993-a17c9200-9df7-11ea-8fe9-9804d4b3eb6b.png)

**Comment by anrelubard** [comment]
Hello!
Have you solved the problem? 
I probably have the same problem.

> java.lang.OutOfMemoryError: Java heap space

![bytcodeview](https://user-images.githubusercontent.com/68691344/88281307-1d0f9800-ccf0-11ea-8f5e-79716d3e0453.jpg)

**Comment by lucafont2** [comment]
> Hello!
> Have you solved the problem?
> I probably have the same problem.
> 
> > java.lang.OutOfMemoryError: Java heap space
> 
> ![bytcodeview](https://user-images.githubusercontent.com/68691344/88281307-1d0f9800-ccf0-11ea-8f5e-79716d3e0453.jpg)

I fixed by first extracting the apk as a zip file, then importing separately 
classes.dex
classes2.dex

**Comment by ThexXTURBOXx** [comment]
For anyone having a `OutOfMemoryError: Java heap space` problem: You need to assign more RAM to BCV. You can do this e.g. by starting BCV with the following arguments:
```
java -Xmx4G -jar bytecode-viewer.jar
```
The `4G` stands for 4 Gigabytes of RAM and this can of course be replaced with an arbitrary number of either Gigabytes (`8G`) or Megabytes (`8192M`). Just be sure to assign enough RAM for your purpose :)
