### ISSUE TITLE
obfuscated dependencies

### ISSUE THREAD

**Issue by KingBowser** [Konloch/bytecode-viewer#28]
It appears that there are two dependencies in [libs](/Konloch/bytecode-viewer/tree/master/libs) which are obfuscated:

- [apktool_2.0.0rc4_obf.jar](/Konloch/bytecode-viewer/blob/master/libs/apktool_2.0.0rc4_obf.jar) 

- [smali-2.0.3-obf-patched.jar](/Konloch/bytecode-viewer/blob/master/libs/smali-2.0.3-obf-patched.jar)

- [dex_obf.jar](/Konloch/bytecode-viewer/blob/master/libs/dex_obf.jar)

What are these doing here. To the best of my knowledge, `dex_obf.jar` is dex2jar and it is more than obvious what `apktool_2.0.0rc4_obf.jar` is. A brief search suggests that this is the only place on the internet (as indexed by google, that is) that even *has* these two files.

These should probably be replaced with non-obfuscated binaries for all intents and purposes.

**Comment by Konloch** [comment]
Refer to https://github.com/Konloch/bytecode-viewer/issues/26
