### ISSUE TITLE
Java heap space

### ISSUE THREAD

**Issue by anrelubard** [Konloch/bytecode-viewer#280]
Hello!
When decompiling the apk, the following error appears! How can the problem be solved?
![bytcodeview](https://user-images.githubusercontent.com/68691344/88281855-13d2fb00-ccf1-11ea-8d80-4b7ad03e8b83.jpg)

**Comment by VADemon** [comment]
Start BCV with more RAM, e.g. `java -Xmx3G -jar BCV.jar`
