### ISSUE TITLE
Update to cfr 0.150

### ISSUE THREAD

**Issue by demiantres** [Konloch/bytecode-viewer#282]
Please update cfr to version 0.150 (https://www.benf.org/other/cfr/).

**Comment by Shadowrs** [comment]
I couldnt figure out how to redistro so I've just replaced the class files inside 2.9.22 with cfr 150 and asm 9.0 (java 16) it wont have support for new stuff like records but here you go https://mega.nz/file/CFwDmAZQ#DVZW4B6mNad4EVc4cGiiy1tnjOCTz8CLUClNahxk6Kc
