### ISSUE TITLE
Error compiling class

### ISSUE THREAD

**Issue by AlvinHacker6** [Konloch/bytecode-viewer#283]
I have an error when compiling
![image](https://user-images.githubusercontent.com/72853967/95955583-ba68fc80-0e05-11eb-89f3-53a9f94126be.png)
what to do?

**Comment by Konloch** [comment]
Try using Bytecode Editing via Krakatau or Smali. To do this go into the main menu View>Pane>Krakatau and enable Bytecode & Editable
