### ISSUE TITLE
Instructions to compile

### ISSUE THREAD

**Issue by Janmm14** [Konloch/bytecode-viewer#289]
As the gradle build PR is apparantly abandoned, here is a linux bash script to create a fat jar.

7z is used as backup because zip complains about jd-gui having multiple identical entries and aborting.
Requires linux packages `p7zip-full` and `zip` additionally to jdk.

Script for automatic building:
```
mkdir out || true
cd out
mkdir classes || true
cd ..

find src -name '*.java' -print > out/source.list

javac -cp "libs/*" -d out -encoding UTF-8 -g -sourcepath src -verbose @out/source.list

cd libs
for file in *.jar
do
	unzip -qo "$file" -x META-INF/* module-info.class -d ../out || 7z x -y -o../out -bd "$file"
done
cd ..

cd out
find . -type f -not -name '*.list' -print > classes.list
cd ..

cd out
jar cfe BytecodeViewer.jar the.bytecode.club.bytecodeviewer.BytecodeViewer @classes.list

zip -j9 BytecodeViewer.jar ../libs/*.txt ../libs/*.zip
cd ..

cd src
find . -type f -not -name "*.java" -exec zip -9 ../out/BytecodeViewer.jar {} +
cd ..
```

**Comment by ThexXTURBOXx** [comment]
See my branch for an up to date Maven build: https://github.com/ThexXTURBOXx/bytecode-viewer

Download can also be found there, containing mostly up-to-date dependencies

**My build can contain many bugs. It works flawlessly for my purposes, but it could maybe break in many other cases (didn't test enough)**

**Comment by nick-botticelli** [comment]
If you also want an up-to-date Gradle build, there is my fork: https://github.com/nick-botticelli/bytecode-viewer which also has a GitHub Actions workflow. All one needs to do to build is `.\gradlew` on Windows or `./gradlew` elsewhere.

Most functionality should work.
