### ISSUE TITLE
Need to add support for JEB and JADX

### ISSUE THREAD

**Issue by Sputuks3** [Konloch/bytecode-viewer#29]
I have both JEB (https://www.pnfsoftware.com/) and JADX (https://github.com/skylot/jadx) decompilers Could you advise how to integrate, write plugin or modify source? Both have cmd and GUI versions. Thanks

**Comment by nirangasandaruwan** [comment]
can you send me JEB decompiler.I coudnt find a free download. 
nirangasandaruwan685@gmail.com

**Comment by nirangasandaruwan** [comment]
Sputuks3 can you please send me the GUI version of the JEB.I cant spend 1000$ to buy this decompiler.here is my mail nirangasandaruwan685@gmail.com.if you know any free downloadable link.let me know

**Comment by Konloch** [comment]
Take a look at the JavaDecompiler class, then KrakatauDecompiler. If you can import the classes needed to decompile take a look at ProcyonDecompiler.

**Comment by nirangasandaruwan** [comment]
Konloch most of the decompilers don't produce semantic code that is not fully readable.that's why I want to give JEB decompiler a try.

**Comment by Sputuks3** [comment]
Bootleg copies of both JEB versions 1.4 and 1.5 are available on the net for download. You might want to try searching first. Please not that you are not allowed to distribute the  decompiler engine with your project, only distribute the API calls as this is how you have almost total control over JEB

**Comment by nirangasandaruwan** [comment]
Sputuks3 License is blacklisted

**Comment by nirangasandaruwan** [comment]
Sputuks3 can you provide me a working link.many thanks to you

**Comment by nirangasandaruwan** [comment]
Sputuks3 I spend many hours but couldn't find Bootleg copies of both JEB versions 1.4 and 1.5 .please help me I'm a beginner android developer.

**Comment by Konloch** [comment]
nirangasandaruwan stop fucking asking for cracked jeb on this ticket, it's not so you can get your pirated software.

**Comment by Sputuks3** [comment]
Ok. So I have created my decompiler of choice by extending Decompiler class. Please advise how to connect this with the GUI

What does the method below do?

if (pane2 == 8) {// JEB
						RSyntaxTextArea panelArea = new RSyntaxTextArea();
						panelArea
						.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
						panelArea.setCodeFoldingEnabled(true);
						panelArea.setAntiAliasingEnabled(true);
						RTextScrollPane scrollPane = new RTextScrollPane(
								panelArea);
						panelArea.setText(Decompiler.jeb.decompileClassNode(cn,b));
						panelArea.setCaretPosition(0);
						panelArea.setEditable(BytecodeViewer.viewer.pane2Editable.isSelected());
						krakatau2 = panelArea;
						krakatau2.addKeyListener(new KeyListener() {  
							public void keyPressed(KeyEvent e) {  
								if ((e.getKeyCode() == KeyEvent.VK_F) && ((e.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
									field2.requestFocus();
								}

								BytecodeViewer.checkHotKey(e);
							}
							@Override public void keyReleased(KeyEvent arg0) { }
							@Override public void keyTyped(KeyEvent arg0) { }  
						});
						panel2.add(scrollPane);
					}

**Comment by Konloch** [comment]
Take a look at the.bytecode.club.bytecodeviewer.gui.ClassViewer.setPanes(), that's used to set the pane variables.

You'll need to add the JMenu item to the.bytecode.club.bytecodeviewer.gui.MainViewerGUI (don't forget to add your new objects to the radio button collections), then extend the saving (in the.bytecode.club.bytecodeviewer.settings) so it can support saving the option of the new decompiler.

Then you'll need to copy what you need inside ClassViewer and just repeat it as needed.

It's a bit tricky at first but once you've got the hang of it it's pretty straight forward.

**Comment by Sputuks3** [comment]
Done that. But code is still not being called

    else if (BytecodeViewer.viewer.panelGroup1.isSelected(BytecodeViewer.viewer.panel1jeb.getModel()))
			pane1 = 8;

**Comment by Sputuks3** [comment]
Ok found the problem. My pane1 pane2 and pane3 were all referring to pane1 due to copy and paste

**Comment by Sputuks3** [comment]
Partial success at last.

![bcv-jeb](https://cloud.githubusercontent.com/assets/1269084/7725277/a4fe50dc-ff2b-11e4-834f-fa5610d7862f.jpg)

**Comment by Konloch** [comment]
Awesome! You should message me on Skype, I'd love to add this officially into BCV with optional support like Krakatau's Python.
