### ISSUE TITLE
The font is too small

### ISSUE THREAD

**Issue by CooperCao** [Konloch/bytecode-viewer#291]
open AndroidManifest.xml ,the font is too small and can't adjust font size.
Can you increase the function of the mouse to adjust the font size?

**Comment by Janmm14** [comment]
Theres a font size option in the top menu somewhere

**Comment by ThexXTURBOXx** [comment]
Should be adjustable here (please report back if that doesn't work):

![grafik](https://user-images.githubusercontent.com/12763829/114472719-18c73a00-9bf3-11eb-9fec-9ff1e3725875.png)

**Comment by Konloch** [comment]
Ctrl + Mouse Wheel can now adjust font as well

**Comment by Owyn** [comment]
Font is still too small, said setting only works on the code panel, nothing else sadly 
![image](https://github.com/Konloch/bytecode-viewer/assets/1309656/80d58daa-5594-4bfd-bf1d-5061a9e14ef1)

**Comment by Janmm14** [comment]
The font size of non code panel is standard windows size, you mgiht want to change scaling to 150% or so if its too small for u?

**Comment by Owyn** [comment]
> The font size of non code panel is standard windows size, you mgiht want to change general windows scaling to 150% or so if its too small for u (monitor settings)?

it's not standard windows size, it's ignoring standard windows size scaling option which I already have set to 150%

**Comment by Konloch** [comment]
You might be able to hold alt / shift and scroll to change the font size

**Comment by Owyn** [comment]
> hold alt / shift 

Doesn't help.

and I have JDK 21.
