### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported api 589824

### ISSUE THREAD

**Issue by wgaylord** [Konloch/bytecode-viewer#295]
```
Skipping: org/spigotmc/builder/Bootstrap.class
java.lang.IllegalArgumentException: Unsupported api 589824
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:57)
	at org.objectweb.asm.tree.ClassNode.<init>(ClassNode.java:163)
	at org.objectweb.asm.tree.ClassNode.<init>(ClassNode.java:149)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.getNode(JarUtils.java:243)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.put(JarUtils.java:79)
	at the.bytecode.club.bytecodeviewer.util.OpenFile.run(OpenFile.java:99)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

I am running bytecode-viewer with Java 16, (only java on my Ubuntu system) and attempting to look at a Jar file.  (Spcifically Spigot's buildtools because it was the only jar I hard easily on hand) I am not sure really what version of java the jar file was built with.

**Comment by ThexXTURBOXx** [comment]
Should be fixed in 2.10.11

**Comment by wgaylord** [comment]
Yep! All fixed.

**Comment by JoeJoe1989** [comment]
Hi, my projects use both asm (7.2) and asm-util (7.1). In order to upgrade my project to JDK 17, I need to update asm to 9.1 which supports JDK 17. However, the build failed due to: 

"Unsupported api 589824" error for asm (9.1) and asm-util (9.1)

If I downgrade asm-util to 7.1, the build succeeded. asm (9.1) and asm-util (7.1)

Not sure if you have any idea. Thanks.

**Comment by ThexXTURBOXx** [comment]
You need to change the ASM Version constant here: https://github.com/Konloch/bytecode-viewer/blob/master/src/main/java/the/bytecode/club/bytecodeviewer/Constants.java#L86

**Comment by JoeJoe1989** [comment]
Sorry, can you please explain a bit more? How would changing the ASM_VERSION resolve the issue I am facing in my own project that directly use asm and asm-util?

**Comment by ThexXTURBOXx** [comment]
In that case, your question is completely unrelated to BCV. Please use ASM's issue tracker or StackOverflow instead
