### ISSUE TITLE
Krakatau missing dependency error

### ISSUE THREAD

**Issue by Janmm14** [Konloch/bytecode-viewer#298]
If you decompile a jar with depenendencies other than JRE, the Krakatau decompilation has to enumerate the jar files from optional dependency folder to multiple -path arguments

**Comment by ThexXTURBOXx** [comment]
Can't reproduce with BungeeCord and Spigot Plugins. Can you send a jar that fails for you or a concrete StackTrace?

**Comment by Janmm14** [comment]
I used ProtocolLib and Krakatau couldn't find org/bukkit/plugin/Plugin although spigot-1.8.8.jar is in the optional lib folder

**Comment by ThexXTURBOXx** [comment]
Still cannot reproduce. Could this be an issue related to Krakatau itself then?

![grafik](https://user-images.githubusercontent.com/12763829/122916955-c24a4a80-d35d-11eb-88f3-bb5cb8b60597.png)

**Comment by Janmm14** [comment]
Scroll down in Krakatau view

**Comment by ThexXTURBOXx** [comment]
I see. It is very weird that this only applies to methods/functions and not fields. I will take a look at that after I fixed the other issue

**Comment by Janmm14** [comment]
I believe Krakatau needs dependant classes only for method calls

**Comment by ThexXTURBOXx** [comment]
Should be fixed in #299
