### ISSUE TITLE
suggestions regarding Krakatau

### ISSUE THREAD

**Issue by Storyyeller** [Konloch/bytecode-viewer#30]
Hi, I just discovered this project. Anyway, I have some suggestions for the Krakatau decompiler and disassembler support. 
- You should disable assertions by passing -O to Python. The assertions are useful for testing or debugging, but for normal use, you're better off disabling them. Disabling assertions also makes things slightly faster. Note that this is an option for python itself, not Krakatau, so the command line would look like python -O Krakatau...
- Likewise, you should pass the -skip option to the decompiler to skip each class or method on errors instead of stopping at the first error. It's better to decompile some classes than none.
- Also, on Windows, Krakatau sanitizes the output paths to avoid collisions, so the path of the output file isn't necessarily the same as the actual name of the class. Even on other OSes, you can get errors if the class name is too long or contains special characters. I'd recommend outputting to a jar/zip file instead, since the output path inside the zip file is always the same as the actual class name. You can do this by passing a path ending in .jar or .zip to -out, e.g. -out temp.jar
- Lastly, Pypy is usually faster than CPython, so I'd recommend using pypy over python when possible.

**Comment by Konloch** [comment]
Thank you very much for this! I'll be sure to implement this features/fixes in the latest release.

**Comment by Konloch** [comment]
Implementing these changes now

**Comment by Konloch** [comment]
* 04/19/2015 - Added -O to be passed for Krakatau Decompiler/Disassembler/Assembler. (Thanks Storyyeller).
 * 04/19/2015 - Added -skip to be passed for Krakatau Decompiler. (Thanks Storyyeller).
 * 04/19/2015 - Changed the warning window for Python to recommend PyPy. (Thanks Storyyeller).

I'll implement the zip output soon, thanks again for the suggestions!

**Comment by Storyyeller** [comment]
By the way, I just pushed some changes to Krakatau that include a major performance improvement, as well as a couple bugfixes and better display for negative and float literals. I'd recommend you update.

**Comment by Konloch** [comment]
Updated, cheers!

**Comment by Storyyeller** [comment]
I just pushed another update, which improves performance in some cases and fixes a few bugs.

Also, the decompiler no longer verifies classes before decompiling, which is a good thing normally, but if you actually want to do verification you'll have to stick to the older version.

**Comment by Konloch** [comment]
Cheers, I'll update this right now

**Comment by Treer** [comment]
With regard to adding "-skip" to line 69 of KrakatauDecompiler.java, could it also be added to line 143?

I'm having trouble decompiling a whole .jar, and I think this is the fix.

**Comment by Konloch** [comment]
Not sure how that got missed! I'll fix that right now, sorry about that.

**Comment by Konloch** [comment]
Pushed, would you be able to pull & compile to verify that fixed it?

**Comment by Treer** [comment]
Thanks!

I'd installed it from the release and didn't have it set up as a compilable project, so once I figured out what was wrong I copied the command-line used by bytecode-viewer into a .bat file and added the -skip argument. The Minecraft snapshot then fully decompiled as far as I can tell, so I suspect it's good.

**Comment by Storyyeller** [comment]
By the way, could you check what kind of errors you're getting? If it's
just a missing class, that's one thing, but if you're getting actual
errors, it might be worth filing a bug against Krakatau.

**Comment by Treer** [comment]
Will keep this in mind. From memory the ones I saw were just missing classes.

**Comment by Storyyeller** [comment]
Just fixed a major bug in Krakatau. Turns out one of the optimizations I added a couple weeks ago sometimes causes it to produce incorrect results.

**Comment by Konloch** [comment]
Updated BCV to latest Krakatau, thanks for alerting me!
