### ISSUE TITLE
Resource editing and display optimization in jar(Or other formats)

### ISSUE THREAD

**Issue by cn-fairy** [Konloch/bytecode-viewer#315]
The current effect is shown in the following figure:
(the procedure shown is for feedback only)
![image](https://user-images.githubusercontent.com/74580422/125042411-5e997e80-e0cc-11eb-90f8-b4623e69dc0e.png)
1.In the middle of a large space is not used, feel a waste of good resources
2.The resource display area on the right side is too small, resulting in poor preview effect
3.No separate search
Although resources can be extracted separately for viewing and modification, it is hoped that they can be viewed and modified through "Bytecode-Viewer".

**Comment by Konloch** [comment]
Thank you, I've fixed this issue for [v2.10.14](https://github.com/Konloch/bytecode-viewer/releases/tag/v2.10.14), the Hex-Viewer should now resize better
