### ISSUE TITLE
Darklaf RSyntaxTheme

### ISSUE THREAD

**Issue by weisJ** [Konloch/bytecode-viewer#317]
https://github.com/Konloch/bytecode-viewer/blob/0325c2008e2629f836d06040b07599233a359d5a/src/main/java/the/bytecode/club/bytecodeviewer/gui/theme/RSTATheme.java#L15

This is just a notice that darklaf offers a customised theme for RSyntaxTextArea, which is optimised for the LaF:

https://github.com/weisJ/darklaf-extensions/blob/master/rsyntaxarea/src/main/java/com/github/weisj/darklaf/extensions/rsyntaxarea/DarklafRSyntaxTheme.java

**Comment by Konloch** [comment]
Thank you for this! The option to use DarkLAF RSyntaxTheme is now added for [v2.10.14](https://github.com/Konloch/bytecode-viewer/releases/tag/v2.10.14)
