### ISSUE TITLE
plz include jadx Decompiler .. 

### ISSUE THREAD

**Issue by Hasan-Uddin** [Konloch/bytecode-viewer#320]
plz include jadx Decompiler ..

**Comment by Janmm14** [comment]
What are its benefits compared to Fernflower, CFR or Procyon?

**Comment by ThexXTURBOXx** [comment]
It is already included
![grafik](https://user-images.githubusercontent.com/12763829/125775568-dcfe465f-6ff7-4562-b194-7ae7c3ca9962.png)
