### ISSUE TITLE
Tracking Code?

### ISSUE THREAD

**Issue by Konloch** [Konloch/bytecode-viewer#35]
I'm wanting to get some user input, I'm personally curious how many people run/install BCV. Because of this I've thought about adding some type of 'tracking code' into BCV for a while, but of course the downside to this is I doubt you guys would enjoy being tracked.

So, should I add a tracker? Should I not? I'm leaning towards adding one, so if you guys don't want one I suggest you reply to here so your concerns can be voiced. If you guys don't want it added it won't be.

However if you guys decide to add it, I'll explain how it'll work:
When you first start BCV, it'll simply prompt you with a menu asking if you would like to 'Ping Back' to BCV's website, alerting that another person has started BCV for the first time. If you select yes, it'll connect to http://bytecodeviewer.com/whatevercounter.php (as an example) to simply increase the integer on BCV's main page. The downsides to this are obviously your IP would be sent to the webserver (it would also be stored to ensure we don't get people trying to input multiple times).

So the choice is yours. I won't implement this system till 2.9.5, and that's probably 1-2 months away. (Also on a side note, expect DJ-Core as the fifth decompiler for 2.9.5 :dancer:)

**Comment by U2ForMeJava** [comment]
Sure, why not? I feel that as long as you give the user the option to 'Ping Back' to the website, this is a nice thing to do. Besides, it's not like the IP can be used to trace someone back, with solely an IP inside a database you can't really do anything, can you?

**Comment by Konloch** [comment]
Thanks for the input, I was thinking the exact same thing, hopefully the rest of the users agree!

**Comment by cemo** [comment]
No problem for me as well.

**Comment by Konloch** [comment]
Alright, I might push 2.9.4b which contains the new tracker code then, I'm glad you guy's are up for it.

The statistics will be posted on https://bytecodeviewer.com

**Comment by Konloch** [comment]
I've decided to just go ahead and push 2.9.5 which contains this, if anyone has any concerns with this feel free to vent it here, I'm still totally open to reverting it back to how it was.

https://github.com/Konloch/bytecode-viewer/releases/tag/v2.9.5 is exactly as 2.9.4 just with the new tracker code.
