### ISSUE TITLE
[How To] run on Fedora Gnu/Linux

### ISSUE THREAD

**Issue by kirantpatil** [Konloch/bytecode-viewer#37]
I could not find any how to install or run guide for Gnu/Linux.

Please send me the steps and can you please maintain a wiki for it in github itself.

Thanks.

**Comment by Konloch** [comment]
won't be adding a wiki here, there's an article on a Java RE related wiki already here https://the.bytecode.club/wiki/index.php?title=Bytecode_Viewer.

To run it on Linux simply install Java with one of the many package managers, then run the BCV Jar.

It's literally just a stand alone program, no install needed.
