### ISSUE TITLE
[How To] apk to java and java to apk

### ISSUE THREAD

**Issue by kirantpatil** [Konloch/bytecode-viewer#38]
Hi,

I would like to convert apk to java and modify java files and again convert them back to apk.

How to do this using bytcode-viewer ?

Thanks.

**Comment by Konloch** [comment]
You literally open the APK with BCV, then select a Java decompiler (Or the Krakatau Bytecode Decompiler), enable editable on that pane. Do the changes you want, File>Compile.

Pretty straight forward once you get the hang of it. If you've got any more questions feel free to ask.

**Comment by Konloch** [comment]
Oh, then simply export as APK to generate the classes.dex file.

**Comment by dmitrybabich** [comment]
I made some changes, and click the File->Compile button. 
How to export as APK? I can't seem to find such a menu item.
