### ISSUE TITLE
AndroidManifest.xml not display correctly in Decoded Ressources

### ISSUE THREAD

**Issue by sudni** [Konloch/bytecode-viewer#41]
Hi, I just update Bytecode Viewer by the version 2.9.5 and the display show AndroidManifest.xml as same manner in Decoded Ressources and on root. In last version in Decoded Ressources I see manifest in xml display format.
Regards
Paul

**Comment by Konloch** [comment]
Could you screenshot what you're talking about?

**Comment by Konloch** [comment]
Haven't been able to recreate this, closing.
