### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by just-rahim** [Konloch/bytecode-viewer#412]
PS C:\Users\john\Downloads> java -jar .\Bytecode-Viewer-2.11.1.jar
Bytecode Viewer 2.11.1 [Fat Jar] - Created by @Konloch
https://bytecodeviewer.com - https://the.bytecode.club
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:183)

**Comment by ThexXTURBOXx** [comment]
Already "fixed" on master. Either enable the Security Manager, take an older version of Java or use this snapshot release of BCV: https://github.com/Konloch/bytecode-viewer/suites/6058420798/artifacts/209066260

**Comment by Konloch** [comment]
[v2.11.2](https://github.com/Konloch/bytecode-viewer/releases/tag/v2.11.2) is live now as well so this should be resolved officially, thank you for reporting this issue!

**Comment by ThexXTURBOXx** [comment]
Your version of BCV is way too outdated. Either use an older version of Java (I would recommend Java 8) or upgrade BCV

**Comment by ricardozv** [comment]
Thanks
