### ISSUE TITLE
Use more modern icons?

### ISSUE THREAD

**Issue by GraxCode** [Konloch/bytecode-viewer#413]
As they look pretty old and "eclipse"-like, maybe the icons here are more suitable: https://jetbrains.design/intellij/resources/icons_list/. These also work very well with @weisJ 's darklaf. He can also help with implementing different icon themes for black or while themes.

**Comment by weisJ** [comment]
With version `3.0.0` most of the icons used by darklaf are now exposed through a public API in `com.github.weisj.darklaf.iconset.AllIcons` (It’s auto generated so can’t be found as source in the repo). The available icons can be found here: https://github.com/weisJ/darklaf/tree/master/iconset/src/main/resources/com/github/weisj/darklaf/iconset

All the icons there are compatible with all LaFs however they are optimised for darklaf.

**Comment by Konloch** [comment]
This is a great suggestion, thank you both! I will implement this when I get a chance but if anyone beats me to it I will gladly pull in any PRs!
