### ISSUE TITLE
Command line parameter to save source

### ISSUE THREAD

**Issue by clviper** [Konloch/bytecode-viewer#42]
Hi there.
First of all, congrats on the awesome project.
I have a feature request. Have the ability to decompile a jar and save all the source code from command line.
This is would help a lot the process of automating the analysis of java source code. 
Thanks

**Comment by Konloch** [comment]
I'll implement this into the next release, thanks for the suggestion!

**Comment by clviper** [comment]
Awesome. Thnks for the feedback.

**Comment by clviper** [comment]
Hi there. Did you had the opportunity to had this feature to the latest release? Dont really find it.

**Comment by Konloch** [comment]
I decided to wait until I've finished the OSGI style implementation before I add more command line options.

It should be in 2.9.7, if not 2.9.8

**Comment by Konloch** [comment]
Confirmed this will be in 2.9.7-preview-3, I'm almost finished this.

**Comment by Konloch** [comment]
2.9.7-preview-3 is now live - https://github.com/Konloch/bytecode-viewer/blob/master/BytecodeViewer%202.9.7-preview-3.jar

Command Line Arguments:
	-help                         Displays the help menu
	-list                         Displays the available decompilers
	-decompiler <decompiler>      Selects the decompiler, procyon by default
	-i <input file>               Selects the input file (Jar, Class, APK, ZIP, DEX all work automatically)
	-o <output file>              Selects the output file (Java or Java-Bytecode)
	-t <target classname>         Must either be the fully qualified classname or "all" to decompile all as zip
	-nowait                       Doesn't wait for the user to read the CLI messages
