### ISSUE TITLE
Wiki site not working!

### ISSUE THREAD

**Issue by tempaccforissue** [Konloch/bytecode-viewer#425]
I went to https://the.bytecode.club, then the Learn tab at the top, I clicked there and then Learn Java Byte Code (link: https://the.bytecode.club/wiki/Learn_Java_Reverse_Engineering) but it shows a cloudflare error. Same for the bycodeviewer.com

**Comment by Konloch** [comment]
Thank you for bringing this to my attention, I've resolved this issue. I am very sorry for the downtime and issues this may have caused!
