### ISSUE TITLE
Add support for ASMifier

### ISSUE THREAD

**Issue by nevack** [Konloch/bytecode-viewer#426]
https://asm.ow2.io/faq.html#Q10

**Comment by Konloch** [comment]
Hello, thank you for the suggestion! ASM Textifier is added in the latest versions, to enable it it's in the top menu View->Pane>ASM Textifiy->Bytecode

**Comment by nevack** [comment]
Hi, yes, I know, but ASM Textifier is not the same as ASMifier.
Textifier reads class files and prints their bytecode.
On the other hand, ASMifier read class file and prints JAVA ASM code, to generate such bytecode.
Please reopen the issue, if ASMifier is not implemented (AFAIK, there's no such option in latest release).

**Comment by Konloch** [comment]
Ooh, thank you for the explanation! I think I understand now. I think this would be a great addition for anyone who is using ASM library in their own codebase, or maybe if they wanted to learn more how ASM works. I will look into adding this, thank you again for the suggestion and the explanation on it!

**Comment by nevack** [comment]
Yes, it will help a lot for any bytecode generation/transformation with Java ASM, like with [AsmClassVisitorFactory](https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/instrumentation/AsmClassVisitorFactory) in Android Gradle Plugin.
Thanks!

**Comment by nick-botticelli** [comment]
I have just added support for this and filed a pull request: #429.

[Here](https://gist.github.com/nick-botticelli/78bbbb90c12d55110f9191fd484dad83) is an example using `the.bytecode.club.bytecodeviewer.Settings` class as an input.

**Comment by nick-botticelli** [comment]
Issue seems to be resolved now that #429 was merged.

**Comment by nevack** [comment]
Yup, tested it out now. Thanks!!

@nick-botticelli P.S. Is it possible to reformat the code produced by ASMifier?

**Comment by nick-botticelli** [comment]
> Yup, tested it out now. Thanks!!
> 
> @nick-botticelli P.S. Is it possible to reformat the code produced by ASMifier?

I am not sure of the existence of code in the project that would reformat the code. Perhaps I can look into it further, but text processing isn't really my cup of tea.

**Comment by nevack** [comment]
> I am not sure of the existence of code in the project that would reformat the code. Perhaps I can look into it further, but text processing isn't really my cup of tea.

Maybe this will help https://github.com/google/google-java-format#as-a-library

**Comment by nick-botticelli** [comment]
> > I am not sure of the existence of code in the project that would reformat the code. Perhaps I can look into it further, but text processing isn't really my cup of tea.
> 
> Maybe this will help https://github.com/google/google-java-format#as-a-library

I finally took an actual look into this, and it seems that `--add-exports` arguments are needed on JDK 16+, so some initial loader or launcher must be used so that the burden of these arguments aren't passed on to the user. Doesn't look super feasible from my point of view. I may look into a proper solution, as it would seem to be a great feature for this application.
