### ISSUE TITLE
Windows EXE files: don't wrap the JAR file inside the EXE

### ISSUE THREAD

**Issue by jpstotz** [Konloch/bytecode-viewer#44]
If I get the situation right, the current download package contains BytecodeViewer three times. One plain JAR file and two times the JAR file wrapped inside an 32/64 bit executable. 

Therefore the content is highly redundant and most users will simply throw away 66% of the downloaded data...
Furthermore virus scanners often block access for a long time while scanning thus large and compressed EXE files.

Therefore it would better to have launcher EXE files that simply use but not wrap the JAR file.
I am not familiar with the used tool Jar2Exe however even Open  Source tools like [Launch4J](http://launch4j.sourceforge.net/) support to create EXE launch applications that do not wrap the JAR file. 

In case of Launch4J only one 32bit EXE file is required as it can automatically detect installed 32bit and 64bit JREs and use it accordingly.

**Comment by Konloch** [comment]
Distribution size isn't really a concern to me.

Launch4J doesn't provide the same features Jar2Exe does (mainly the command line option which is used to integrate opening .class and .apk files directly on windows).

**Comment by jpstotz** [comment]
If the download speed of GitHub would be faster I would agree that the distribution size does not matter (I get only 500k/sec on a 100MBit+ connection). 

Regarding Launch4J and the command line option I am not sure if we are talking about the same topic. But I have created a very simple Launch4J wrapper and using your modified your registration script successfully registered apk files with bytecode-viewer on Windows 7. Double clicking the apk file opens bytecode-viewer and the the apk in it.

**Comment by Konloch** [comment]
Gonna take a look at Launch4J again, thanks for the suggestion.

**Comment by Konloch** [comment]
Using Launch4J for 2.9.6 <3
