### ISSUE TITLE
cycle through all the results of `Quick file search` in the file tree

### ISSUE THREAD

**Issue by sify21** [Konloch/bytecode-viewer#466]
Is there a way to scroll the file tree to the next entry when doing `Quick file search`?
For example in the following image, there are license files under `license` folder, but every time I hit `enter`, the file tree will scroll to the first entry that's found.
<img width="488" alt="图片" src="https://user-images.githubusercontent.com/11829223/220515472-d943c623-5012-4e25-be0a-cd865ddf1cee.png">

Others have also found the same behavior. The original conversation on discord :
https://discord.com/channels/856606904511103007/862159917338198026/1077777554494193674

**Comment by Konloch** [comment]
Thank you for your suggestion! I've included this for the next release. I've also added a toggle so you can automatically open the file found, then cycle thru to the next one.

A preview for this feature is located at https://github.com/Konloch/bytecode-viewer/actions/runs/7245057185
