### ISSUE TITLE
build cannot found `com.github.ThexXTURBOXx.dex2jar:d2j-external:v59`

### ISSUE THREAD

**Issue by alan717** [Konloch/bytecode-viewer#473]
Hello , I clone the repo with the latest commit, but got this message:  
```
[WARNING] The POM for com.github.ThexXTURBOXx.dex2jar:d2j-base-cmd:jar:v59 is missing, no dependency information available
[WARNING] The POM for com.github.ThexXTURBOXx.dex2jar:d2j-external:jar:v59 is missing, no dependency information available
Cannot resolve com.github.ThexXTURBOXx.dex2jar:d2j-external:v59
Cannot resolve com.github.ThexXTURBOXx.dex2jar:d2j-base-cmd:v59
Could not find artifact com.github.ThexXTURBOXx.dex2jar:d2j-base-cmd:pom:v59 in google (https://maven.google.com/)

```
It looks like cannot found TheXTURBOXx 's github repo in google's repostory.
How to resolve this dependencies?

**Comment by acodervic** [comment]
@alan717 How do you fix this problem? Please help me. I have the same problem too.

**Comment by deadlocklogic** [comment]
https://github.com/Konloch/bytecode-viewer/blob/ca894b3d1666a39280918198934ed165274846ae/pom.xml#L34
Replace:
`<dex2jar.version>v59</dex2jar.version>`
with
`<dex2jar.version>35</dex2jar.version>`
in `pom.xml`.
