### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by TheBiblMan** [Konloch/bytecode-viewer#48]
Convert the entire project into modules or bundles and either make a loader or try an OSGI container. 
The amount and size of the dependencies makes it take too long to clone the repository.

**Comment by Konloch** [comment]
I've been planning on doing this eventually, just been busy as fuck lately.

Eventually I'll clean out the repo and make it nice, probably in a week or so when I've got some actual free time.

Thanks for the feed back!

**Comment by widd** [comment]
Why not just move as much as possible to a build tool like gradle or maven? Gradle would probably be a better option as it's easier to integrate local libs with it (such as Bibl's ASM jar).

**Comment by TheBiblMan** [comment]
noooo
osgi

**Comment by widd** [comment]
YOU CAN'T HIDE FROM BUILD TOOLS FOREVER BIBL

**Comment by TheBiblMan** [comment]
o
   s
     g
      iiiiiiiiiiiiiiiiiiiii

**Comment by Konloch** [comment]
almost osgi implemented \o/
