### ISSUE TITLE
Linux application folder

### ISSUE THREAD

**Issue by dakralex** [Konloch/bytecode-viewer#481]
On Linux, the program creates a `.Bytecode-Viewer` folder on the users' home directory. This folder could be appropriately placed inside either the `~/.local/share` or `~/.config` folder, where application files should reside normally to declutter the home directory.

Is there a reason that this is in the home directory itself?

**Comment by Konloch** [comment]
Same issue as: https://github.com/Konloch/bytecode-viewer/issues/250 - This is planned to come in a future update, please feel free to publish a PR, or we will plan on publishing one soon! Thank you for the suggestion!
