### ISSUE TITLE
Reload jar?

### ISSUE THREAD

**Issue by TheBiblMan** [Konloch/bytecode-viewer#49]
Click button and reload jar into viewer?

**Comment by tastybleach** [comment]
ya i'd like 2 update jar so i can see new changes atm it ddoesnt but if u do just call he, supercheessee

**Comment by Konloch** [comment]
Might be added for 3.0.0, planning on doing some workspace related changes so it's more like JEB

**Comment by afffsdd** [comment]
yes plz

**Comment by Konloch** [comment]
great news, this will probably be added into 2.9.8 thanks to the new file system implementations

**Comment by Konloch** [comment]
Added
