### ISSUE TITLE
How about user font control

### ISSUE THREAD

**Issue by limelect** [Konloch/bytecode-viewer#54]
I need glasses to read
need font control (bigger fonts) all over the program.
Even the about is not readable (for me) 

Can you designate on the pan which decompiler it is using for clarity

**Comment by Konloch** [comment]
Consider it done amigo! :D

I'll work on implementing this right now.

**Comment by limelect** [comment]
thanks

**Comment by Konloch** [comment]
Just pushed the src that contains the new font selector - http://i.imgur.com/3a0iz4K.png

If you'd like to try it out simply download the src, load it into eclipse and set the library jars for your classpath.

Till then I'm gonna probably wait a bit till I push 2.9.7, thanks for your suggestion!

**Comment by Konloch** [comment]
a 2.9.7 preview is out which contains the font selection :D
