### ISSUE TITLE
2.9.6

### ISSUE THREAD

**Issue by U2ForMeJava** [Konloch/bytecode-viewer#55]
Hello,

Jar 2.9.6 seems corrupt? It's giving me end of file errors. I didn't know if you were aware so I posted this.

Have a nice (hot, so very very hot. So unbearable hot...) day,

U2

**Comment by Konloch** [comment]
Where did you download the jar from?

Both the jar from the repo and the jar from https://github.com/Konloch/bytecode-viewer/releases/tag/v2.9.6 work for me.

Try to redownload it, if github is still having issues for you I can mirror it on http://bytecodeviewer.com if you'd like.
