### ISSUE TITLE
After bug 56 if i try to load a good apk

### ISSUE THREAD

**Issue by limelect** [Konloch/bytecode-viewer#57]
After bug #56 if i try to load a good apk the old error stay
I have to close the program and open again to make it work

**Comment by Konloch** [comment]
I believe I've patched the issue but I'm unable to replicate it on my end, I'll need to wait for a mirror on that APK.

Thanks for the report!

**Comment by limelect** [comment]
Send you on #56 plz acknowledge you got it

**Comment by limelect** [comment]
https://dl.dropboxusercontent.com/u/91173792/Windfinder_1.9.3.apk

**Comment by Konloch** [comment]
Fixed, cheers!
