### ISSUE TITLE
ClassNode is null for CodeSequenceDiagram

### ISSUE THREAD

**Issue by Choonster** [Konloch/bytecode-viewer#58]
This may be related to the fix for #53.

I get the "ClassNode is null for CodeSequenceDiagram" message when attempting to view the code sequence diagram for [this class](https://onedrive.live.com/redir?resid=5205E35027C028A!813&authkey=!ANUmA8-G-yCXxh0&ithint=file%2cclass) and every class I've tried in [this JAR](https://onedrive.live.com/redir?resid=5205E35027C028A!814&authkey=!AD6NvH66d_4gQFo&ithint=file%2cjar) (same class and JAR from the last issue).

**Comment by Konloch** [comment]
This has been fixed :)

If you'd like to try the patch out on your end simply download the latest source, and in the.bytecode.club.bytecodeviewer.gui.ClassViewer remove this line:

 public ClassNode cn;

Then build/run it
