### ISSUE TITLE
Suggestion: Clickable class/method names

### ISSUE THREAD

**Issue by Jofkos** [Konloch/bytecode-viewer#62]
It would be nice if you could click on type/method/field names to get to their declaration.

**Comment by Konloch** [comment]
Could you visual what you mean?

**Comment by Jofkos** [comment]
I mean like it's done in JD-Gui or in Eclipse. All known classes are clickable, and, when you click them, it opens that class. Same thing when you click on a method (knownClass.method("")), it opens the class the method is in and jumps to that method.

**Comment by Konloch** [comment]
Ah, I see. This may be possible for 3.0, I'd need to look into it.

**Comment by afffsdd** [comment]
it would be huge to be able to put your caret on a label in the bytecode view and have the references to that label highlighted.

**Comment by alias1** [comment]
+1, this would make things so much nicer!

**Comment by Janmm14** [comment]
Why not export the whole decompiled code to your ide which has these features already.

**Comment by alias1** [comment]
@Janmm14 While that's doable and a workaround, for the same reasons that I would choose to use an integrated GUI tool like this rather than passing all the files into a command line decompiler and then using my IDE.

**Comment by Konloch** [comment]
@Bl3nd added this in #513 - It will be in the next BCV update

For now you can test it out by using the build snapshot - https://github.com/Konloch/bytecode-viewer/actions/runs/11042465170
