### ISSUE TITLE
bytecode tableswitch deassemble broken

### ISSUE THREAD

**Issue by afffsdd** [Konloch/bytecode-viewer#65]
last case statement does not show in the switch statement.

not default case, the last normal case

for example open up a zkm flow obfuscated strings class and look at the switch statements in the decryptor method (<clinit>)

**Comment by TheBiblMan** [comment]
can confirm this is broken, mb cuz this originally came from my (bad) implementation of an instruction printer.

**Comment by Storyyeller** [comment]
Just to clarify, this affects Konloch's disassembler, not Krakatau, right?

**Comment by Konloch** [comment]
yeah not krakatau

**Comment by Konloch** [comment]
Could you please verify if this issue is persistent in 2.9.9 preview 2 - https://github.com/Konloch/bytecode-viewer/blob/master/BytecodeViewer%202.9.9-preview2.jar

Did a cheaphax, not entirely convinced that'll fix it, but it's worth a shot.

**Comment by afffsdd** [comment]
fixed maybe
