### ISSUE TITLE
unadded opcode on invokedynamic

### ISSUE THREAD

**Issue by vilmosnagy** [Konloch/bytecode-viewer#66]
Hi!

If I try to decompile some code with a lamdba function, or a method reference in it, I get an __UNADDED OPCODE__ message in the decompiled byte code.

For example, the following lines:

    list02.forEach(i -> add02(i));
    list03.forEach(Main::add03);

results the following:

    L3 {
        getstatic hu/package/lambda/Main.list02:java.util.List
        UNADDED OPCODE:     invokedynamic org.objectweb.asm.tree.InvokeDynamicInsnNode@34ffbfae
        invokeinterface java/util/List forEach((Ljava/util/function/Consumer;)V);
    }
    L4 {
        getstatic hu/package/lambda/Main.list03:java.util.List
        UNADDED OPCODE:     invokedynamic org.objectweb.asm.tree.InvokeDynamicInsnNode@6af5c84c
        invokeinterface java/util/List forEach((Ljava/util/function/Consumer;)V);
    }

**Comment by TheBiblMan** [comment]
the bytecode printer is ugly and not 100% perfect. i want to fix it but the code base in general is a mess and there is just too many other things that have to be focused on at the moment. you can add a case for the instruction here, however: https://github.com/Konloch/bytecode-viewer/blob/master/src/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java#L132
