### ISSUE TITLE
v2.9.8 no longer works on Java 1.7

### ISSUE THREAD

**Issue by Lanchon** [Konloch/bytecode-viewer#73]
v2.9.8 release no longer works on Java 1.7 and seems to require Java 1.8. Please downgrade or cross-compile to 1.7 if possible, 1.7 is the standard release in many important linux distros and Android development is mostly done in 1.7 too.

**Comment by Lanchon** [comment]
Exception in thread "main" java.lang.UnsupportedClassVersionError: the/bytecode/club/bytecodeviewer/BytecodeViewer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
...

**Comment by Konloch** [comment]
Fixed, sorry about that.

Please redownload, all of the compiled jars have been fixed for 1.7, could you please verify that it's working now?

**Comment by Lanchon** [comment]
wow that was fast thanks!!! give me a minute...

**Comment by Lanchon** [comment]
confirm fixed, thank you!! :)

**Comment by Konloch** [comment]
Cheers :dancer:
