### ISSUE TITLE
Cannot decompile APK

### ISSUE THREAD

**Issue by KingWu** [Konloch/bytecode-viewer#76]
Just drag and drop an APK. Nothing happen. Any system requirements needed?

my java version
java version "1.7.0_79"

Thanks

**Comment by KingWu** [comment]
Sorry. Any guideline which teach how to decompile an apk?

**Comment by Konloch** [comment]
which APK are you trying to open? On 2.9.8 I can open APKs fine, you should just be able to drag and drop, or try opening via file>open.

Also, if it still fails try selecting Enjarify for jar conversion.

**Comment by KingWu** [comment]
i try 
https://dl.dropboxusercontent.com/u/91173792/Windfinder_1.9.3.apk

it fails

**Comment by limelect** [comment]
Windfinder_1.9.3.apk
on BytecodeViewer 2.9.7-preview it i OK
on 2.9.8 it fails

**Comment by Konloch** [comment]
Are you using Enjarify for jar conversion or Dex2Jar? There are two ways to convert APKs now.

**Comment by limelect** [comment]
I did all 3 view pan NONE as a starter
Windfinder_1.9.3.apk
But same with other apk's

Log
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:867)

Log
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

brut.a.a.e: resource spec: 0x01010462
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:863)

**Comment by Konloch** [comment]
Yeah that's decompiling, not APK conversion.

Go into Settings>APK Conversion>Dex2Jar and Enjarify.

Try both, at least one should convert the APK, I'll test this out personally when I have more time.

Thanks for the reports/information guys!

**Comment by Konloch** [comment]
Actually I think I know what the issue is, for now use enjarify.

**Comment by limelect** [comment]
More bugs
I open a .dex file
press class Ok
open full view
press anothe class
open only on right pan left pan is gray.1/3 screen;
pressed refresh the the naxt class open full screen.

**Comment by limelect** [comment]
No tried "for now use enjarify." on a few apk's no !!1
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:867)

same problems

**Comment by Konloch** [comment]
I've reverted the dex2jar library to it's previous version, could you please verify if it's working now.

@limelect please create a new ticket for each bug, thank you.

**Comment by limelect** [comment]
Could you please verify if this issue is persistent in 2.9.9 preview 2 - https://github.com/Konloch/bytecode-viewer/blob/master/BytecodeViewer%202.9.9-preview2.jar

Bytecode Viewer Version: 2.9.9, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:865)

**Comment by killolol** [comment]
Getting the same error, no matter if I use enjarify, or d2j. Bud for example jadx works great.
