### ISSUE TITLE
Bytecode_Viewer\bcv_temp\blah blah.jar not found

### ISSUE THREAD

**Issue by XNepster** [Konloch/bytecode-viewer#77]
I downloaded and test three different version of byteCode but giving the same error. What should i do know.

**Comment by Konloch** [comment]
What operating system are you on?
Are you able to run BCV with a command prompt/terminal and paste the contents?
Could you also provide the exact JRE you're using (java -version in terminal).

Lastly, try the 'fatjar' version located on the git, does it work with that version?


Cheers!

**Comment by Konloch** [comment]
Anyone else experienced this issue? If so could you please answer the above questions, cheers.

**Comment by DarioI** [comment]
I had the same error, tried with fatjar version and received the following again:


Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: true

java.io.FileNotFoundException: /Users/DarioIT/.Bytecode-Viewer/bcv_temp/aubhOhyFnPTKuqNEAyTpDrBFw.jar (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at the.bytecode.club.bytecodeviewer.JarUtils.loadClasses(JarUtils.java:83)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:878)
'

Running on OS X 10.10.4 and Java:

java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

**Comment by Konloch** [comment]
Could you please tell me what you did to throw that exception?

**Comment by DarioI** [comment]
I open the Add... menu action, tried to load an apk and this happened. Tried several times, several times the same error.

**Comment by Konloch** [comment]
Could you please run this from your terminal as java -jar "bytecodeviewer 2.9.9.jar" and send everything printed out here?

Also, could you please go to your Settings> and tell me which APK Conversion you have selected, and if 'Decode APK Resources' is toggled.

Cheers!

**Comment by android-kaizen** [comment]
Same here when dropping an .apk.
Say the file is missing
On Windows 10

**Comment by didlich** [comment]
same problem

Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

dex2jar /home/xxxx.apk -> xxxxx-dex2jar.jar
java.io.FileNotFoundException: /home/xxxx/.Bytecode-Viewer/bcv_temp/xPyaEQGmUzCuSGTYcWLpgDwnc.jar (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at the.bytecode.club.bytecodeviewer.JarUtils.loadClasses(JarUtils.java:83)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:878)

**Comment by miller93** [comment]
You need to configure your environment variables, JAVA_HOME and PATH.

JAVA_HOME must contain the path to java, and you should add %JAVA_HOME%\bin to PATH

**Comment by Silur** [comment]
anything new on this issue? I got the same error

**Comment by StefaanSeys** [comment]
can confirm this issue, got the same error

**Comment by bmeike** [comment]
Another example:
`bmeike>java -jar BytecodeViewer\ 2.9.8.jar 
https://the.bytecode.club - Created by @Konloch - Bytecode Viewer 2.9.8
Checking & Deleting foreign/outdated libraries
Loading libraries...
Loading library apktool_2.0.1_obf-2.jar
Succesfully loaded apktool_2.0.1_obf-2.jar
Loading library baksmali-2.0.3_obf.jar
Succesfully loaded baksmali-2.0.3_obf.jar
Loading library byteanalysis-1.0.jar
Succesfully loaded byteanalysis-1.0.jar
Loading library cfr_0_115.jar
Succesfully loaded cfr_0_115.jar
Loading library commons-codec-1.9.jar
Succesfully loaded commons-codec-1.9.jar
Loading library commons-compiler.jar
Succesfully loaded commons-compiler.jar
Loading library commons-io-2.4.jar
Succesfully loaded commons-io-2.4.jar
Loading library commons-lang3-3.3.2.jar
Succesfully loaded commons-lang3-3.3.2.jar
Loading library dex_obf.jar
Succesfully loaded dex_obf.jar
Loading library fernflower-2016.jar
Succesfully loaded fernflower-2016.jar
Loading library imgscalr-lib-4.2.jar
Succesfully loaded imgscalr-lib-4.2.jar
Loading library janino.jar
Succesfully loaded janino.jar
Loading library jar-rename-1.6.jar
Succesfully loaded jar-rename-1.6.jar
Loading library jasmin-p2.5.jar
Succesfully loaded jasmin-p2.5.jar
Loading library jd-gui-1.0.0-RC4.jar
Succesfully loaded jd-gui-1.0.0-RC4.jar
Loading library jgraphx.jar
Succesfully loaded jgraphx.jar
Loading library procyon-decompiler-0.5.30.jar
Succesfully loaded procyon-decompiler-0.5.30.jar
Loading library rsyntaxtextarea.jar
Succesfully loaded rsyntaxtextarea.jar
Loading library slf4j-api-1.7.18.jar
Succesfully loaded slf4j-api-1.7.18.jar
Loading library slf4j-nop-1.7.18.jar
Succesfully loaded slf4j-nop-1.7.18.jar
Loading library smali-2.0.3-obf-patched.jar
Succesfully loaded smali-2.0.3-obf-patched.jar
`

Drop classes.dex into UI window:
 
`java.io.FileNotFoundException: /Users/bmeike/.Bytecode-Viewer/bcv_temp/hYjqieUPRdsEjxHDDyPjZumZl.jar (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at the.bytecode.club.bytecodeviewer.JarUtils.loadClasses(JarUtils.java:83)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:899)

`

**Comment by Flightkick** [comment]
Same here, the .Bytecode-Viewer/bcv_temp directory doesn't get created. It's parent .Bytecode-Viewer also isn't created. Hence the jar file cannot be found.

**Comment by stepanhack** [comment]
Fixed after naming the apk to "a.apk"... I haven't looked at the code at all but I assume it runs into problems when the filename of the apk has a space or certain special characters.

**Comment by Kishanjvaghela** [comment]
Anyone get the solution?

**Comment by stepanhack** [comment]
@Kishanjvaghela Rename your apk file to a single letter like "a.apk" ... This fixed the problem for me

**Comment by geocine** [comment]
@stepanhack thanks, that worked :dancer:

**Comment by magneticflux-** [comment]
It seems to be an issue with special characters in the file name. Try making your filename match this regex: `[A-z0-9 ]+`

**Comment by fritz-net** [comment]
for me also underscores and points work
`[_.A-z0-9 ]+`

**Comment by bydylo** [comment]
I'm also having some problems with BCV

**Comment by bydylo** [comment]
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: true

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI$19$1$2.run(MainViewerGUI.java:1239)

**Comment by Konloch** [comment]
I've done a couple tests and this should be fixed in the latest version, if it's not please create a new issue or E-Mail me. Thanks for all the reports and help guys.
