### ISSUE TITLE
LICENSE contains incorrect license

### ISSUE THREAD

**Issue by SalusaSecondus** [Konloch/bytecode-viewer#78]
The LICENSE file contains the GNU Free Documentation License rather than the (apparently correct) Copyleft license.

https://raw.githubusercontent.com/Konloch/bytecode-viewer/master/LICENSE

**Comment by Konloch** [comment]
Yeah I noticed that a while ago, I'll fix it eventually.

**Comment by Konloch** [comment]
fixed, it's now the proper software GNU copyleft license.
