### ISSUE TITLE
Can't open classes if folder is dragged into window

### ISSUE THREAD

**Issue by diesieben07** [Konloch/bytecode-viewer#80]
Works fine if .class files or .jar files are used. Video demonstration: https://www.dropbox.com/s/7ugq6szn4xfa6zm/2015-08-11_00-07-50.mp4?dl=0

(I can reproduce this with 2.9.8 and also the 2.9.9 preview).

**Comment by Konloch** [comment]
Thanks for this report! I'll fix this as soon as I can.

**Comment by diesieben07** [comment]
:+1: Thanks for your great work on this, I use it daily.

**Comment by Konloch** [comment]
:heart: Glad I could make something that's helped :D

**Comment by alias1** [comment]
This seems to be fixed now in 2.9.8, can probably be closed.

**Comment by alias1** [comment]
Any plans for when this might make it in?

**Comment by Konloch** [comment]
This seems to be fixed in the latest version, if it's not just comment here or open a new issue
