### ISSUE TITLE
Some bytecode crackmes

### ISSUE THREAD

**Issue by Storyyeller** [Konloch/bytecode-viewer#81]
I noticed you had a page for Java bytecode crackmes. Here are some old crackmes which I hope you'll find interesting. They're handwritten Java bytecode with techniques that you won't find elsewhere.

http://crackmes.de/users/warsaw

Sorry if this isn't the right place for this, but I'm not sure where else to submit them.

**Comment by Konloch** [comment]
Cheers, I'll add this to the TBC crack me page soon!
