### ISSUE TITLE
2.9.9 dose not open any APK

### ISSUE THREAD

**Issue by limelect** [Konloch/bytecode-viewer#82]
Could you please verify if this issue is persistent in 2.9.9 preview 2 - https://github.com/Konloch/bytecode-viewer/blob/master/BytecodeViewer%202.9.9-preview2.jar

Bytecode Viewer Version: 2.9.9, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:865)

**Comment by Konloch** [comment]
You're unable to open ANY APKs?

1) Is Enjarify selected or Dex2Jar?
2) Have you tried multiple APKs or just 1-2?
3) Do you have Settings>Delete outdated/foreign libs selected?

**Comment by limelect** [comment]
3) on
2) some will dicompile sending you link
1)Dex2Jar
found a new bug
after the problem a new will not help. a GOOD diconmpiled will not dicompile
try Windfinder_1.9.3.apk this one makes all the problems but others too some OK

Try with a CLEAN start which mean close your software and start again otherwise problems
the new funcion dose not always help!!!

https://dl.dropboxusercontent.com/u/91173792/Android_Dicompile.zip
plz tell me you got the zip

**Comment by Konloch** [comment]
I am able to open Windfinder_1.9.3.apk on 1.9.8 and 1.9.9 using both Enjarify and Dex2Jar.

There's one issue with Dex2Jar that I'm planning on fixing - https://github.com/Konloch/bytecode-viewer/issues/94

Closing this for now, if you're still experiencing this issue feel free to post here or make a new bug ticket, I'll fix it asap.

Cheers!
