### ISSUE TITLE
Potential license conflicts

### ISSUE THREAD

**Issue by CunningLogic** [Konloch/bytecode-viewer#83]
I am by no means a licensing/law expert, but it seems there may be some licensing conflicts with some files in the repo. The only licensing details I can find seem to be GPLv3

smali seems to be bsd and apache
apktool seems to be bsd and apache
enjarify seems to be apache
etc

Would it be appropriate to include license details for all of these?

**Comment by Konloch** [comment]
BCV code (the.bytecode.club.bytecodeviewer.*) is GPLv3, that license doesn't apply to any of the libraries BCV uses.

**Comment by CunningLogic** [comment]
Since your distributing them along with BCV, I believe you should be including the appropriate license for them.

From enjarify (would apply to others included in your repo most likely):

"4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) **You must give any other recipients of the Work or
          Derivative Works a copy of this License**; and"

I could be wrong, and personally don't care, however it looked like a neat project and thought I should point that out.

**Comment by Konloch** [comment]
Probably, if one of the authors contacts me regarding this I'll do it.

**Comment by CunningLogic** [comment]
While I don't agree with your approach to honoring licenses in your project (you obviously care about your own code's license in some way, since you used a GPL license), I'll consider it closed.

**Comment by Konloch** [comment]
Nah, I added the license as a formality. I really couldn't care less about the license (It was the wrong license for 10 months prior to fixing this recently).

As for honoring other licenses, if any of the authors of those libraries feel I'm not honoring it, they can contact me here.

**Comment by CunningLogic** [comment]
If you don't care, then why not use a less restrictive license? or public domain it?

**Comment by Konloch** [comment]
I see no reason not to beyond the fact I'd need to change a bunch of files.

**Comment by tastybleach** [comment]
fake and gay

**Comment by Storyyeller** [comment]
IANAL, but as I understand it, public domain is actually a bad idea because it doesn't have the same legal protection that a real licence does, and not all countries even recognize public domain.

**Comment by CunningLogic** [comment]
Doesn't matter, its obvious that no one cares about licensing of software.

**Comment by Storyyeller** [comment]
Lawyers care a great deal. And by extension, anyone who is big enough to be sued.

**Comment by CunningLogic** [comment]
Was referring to above comments in jest. GPL isn't recognized/supported everywhere either.

**Comment by Konloch** [comment]
Licenses have been added since aug 18th, cheers.
