### ISSUE TITLE
Missing Images on Linux

### ISSUE THREAD

**Issue by maaatts** [Konloch/bytecode-viewer#84]
![Screenshot](http://i.imgur.com/cyGgoCD.png)

Images next to `Files` and `Workspace` are missing.

Arch Linux
GNOME 3
OpenJDK 1.8.0_60

**Comment by maaatts** [comment]
I hit submit too early :(
Images next to `Files` and `Workspace are missing`.

Arch Linux
GNOME 3
OpenJDK 1.8.0_60

**Comment by Konloch** [comment]
I'll see what I can do about this, cheers!
