### ISSUE TITLE
Minimizing package

### ISSUE THREAD

**Issue by Wdestroier** [Konloch/bytecode-viewer#90]
When I open a package and open a class, then for example i close the class, if I click on the "+" button to "minimize"/close the package, it reopen the last opened class in this package(and yes, it "minimize"/close the package, but open the last opened class too(and if i don't open any class(just open and close the package for example) "works fine" )).

**Comment by Konloch** [comment]
Could you please tell me which version you're having this issue on?

**Comment by Konloch** [comment]
Ah, actually I just replicated this issue myself. Fixing now.

**Comment by Konloch** [comment]
Cheaphax fix applied, will push the code soon, thanks for the report!
