### ISSUE TITLE
HighDPI Issue

### ISSUE THREAD

**Issue by sh1ftchg** [Konloch/bytecode-viewer#91]
On high DPI operating systems, specifically windows, there's an issue with java, specifically the tree api.
![issue_dpi](https://cloud.githubusercontent.com/assets/13605760/10260557/86319444-693d-11e5-8bde-008576848b46.png)
Notice on the two tree lists there's an incorrect height calculation at play. While it is a bug with Java, there's a quick fix you can apply to future versions which eliminates the problem in its entirety. Place the following code

            // HIGHDPI FIX
            Font font = UIManager.getFont("Tree.font");
            BufferedImage image = new BufferedImage(1, 1, BufferedImage.TYPE_INT_RGB);
            Graphics g = image.getGraphics();
            int fontHeight = g.getFontMetrics(font).getHeight();
            int rowHeight = (int) UIManager.get("Tree.rowHeight");
            if (rowHeight < fontHeight) {
                UIManager.getDefaults().put("Tree.rowHeight", fontHeight);
            }

immediately after 

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

in ByteCodeViewer.java. Then, everything looks good!

Thanks.

**Comment by Konloch** [comment]
Oop, thanks for the fix.

I'll apply this once I get some free time, cheers!

**Comment by Konloch** [comment]
Finally added, thanks for this!
