### ISSUE TITLE
Plugin ShowMainMethods

### ISSUE THREAD

**Issue by sh1ftchg** [Konloch/bytecode-viewer#92]
The code is not correct, and will report false positives the JVM does not consider. Furthermore, this speeds it up significantly in the process of correcting them. (Checking the access...) 

**References**
java.c:

``` c
mainID = (*env)->GetStaticMethodID(env, mainClass, "", "([Ljava/lang/String;)V");
```

JVM Spec:

> The Java Virtual Machine then links the initial class, initializes it, and invokes
> the **public** class method **void main(String[])**.

**Solution**
I took the liberty of also improving its performance in producing the output and fixing a common issue with a mutable library such ASM's tree api! Assume, always, that all other programmers are idiots and compensate for that inevitability: NEVER compare a field that could be null by its equals method as it will throw a NullPointerException... Especially in comparison to a static constant: Like string literals.

``` java
    private static final int PUBLIC_STATIC = Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC;

    /**
     * sh1ftchg - 03OCT15 - Optimized and corrected common java programming issues.
     *
     * @param classNodeList
     */
    @Override
    public void execute(ArrayList<ClassNode> classNodeList) {
        PluginConsole frame = new PluginConsole("Show Main Methods");
        StringBuffer s = new StringBuffer();
        for (ClassNode c : classNodeList) {
            for (Object o : c.methods) {
                MethodNode m = (MethodNode) o;
                if ((m.access & (PUBLIC_STATIC)) != PUBLIC_STATIC) {
                    if ("main".equals(m.name) && "([Ljava/lang/String;)V".equals(m.desc))
                        s.append(c.name).append(".main([Ljava/lang/String;)V\n");
                }
            }
        }
        int size = s.length() - 1;
        if (size > 0) {
            s.setLength(-1);
            frame.appendText(s.toString());
        } else {
            frame.appendText("No main methods found.");
        }
        frame.setVisible(true);
    }
```

**Comment by Konloch** [comment]
Sorry about the late reply, been swamped with work lately.

When I added this code I wasn't able to get any main methods from any jars I tried.

**Comment by sh1ftchg** [comment]
That was my stupid mistake on the access check!
               if ((m.access & (PUBLIC_STATIC)) == PUBLIC_STATIC) {

Fixes it.

**Comment by Konloch** [comment]
Cheers! I'll slap this into BCV later today.
