### ISSUE TITLE
Bytecode Decompiler Issues

### ISSUE THREAD

**Issue by sh1ftchg** [Konloch/bytecode-viewer#93]
ASM actually provides a mechanism for printing bytecode, which is ignored by the bytecode viewer.

As is tradition, here's the solution. Use **org.objectweb.asm.util.Textifier**... Furthermore, please add a new bytecode decompiler... With all the libraries attached already,  may as well package up tools.jar from your jdk install directory, use com.sun.tools.javap.Main, call it with the same arguments you use to call javap... The executable is literally just a JVM launcher which calls this method directly. I tried to find an article to cite, but couldn't... Instead here's proof from IDA.

![javap](https://cloud.githubusercontent.com/assets/13605760/10264590/1089d15e-69d6-11e5-90ee-52620183105f.png)

**Comment by Konloch** [comment]
I was thinking about adding another Bytecode Decompiler, I believe Procyon has one built inside of it as well.

I'll look into adding this for the 3.0 release.

**Comment by jredfox** [comment]
https://asm.ow2.io/ might help. you can then convert it to text by simply using a class reader then converting it to text.

Also allows for writing the bytes to. However the current classwriter is flawed check out
https://github.com/llbit/ow2-asm/blob/master/test/conform/org/objectweb/asm/ClassWriterComputeFramesTest.java

It can be even faster using a cache my adjustments here using a cache to speed up the process. Ignore the obsucation and deobfuscation that is an adustment to make it work with minecraft forge
https://github.com/jredfox/classwriter_mod/blob/master/src/main/java/com/evilnotch/classwriter/MCWriter.java

**Comment by Konloch** [comment]
Both disassemblers have been added now, thank you for the suggestion/solutions @sh1ftchg!
