### ISSUE TITLE
More debug output from bytecode disassembler

### ISSUE THREAD

**Issue by samczsun** [Konloch/bytecode-viewer#96]
Such as source file name

**Comment by Konloch** [comment]
Is there anything else you would like debugged?

**Comment by samczsun** [comment]
Perhaps the attributes (Classes, Fields and Methods) as well. Just in case someone forgets to delete or tries to hide information within attributes

**Comment by Konloch** [comment]
Sounds good, I'm going to add a few things to the BCV Bytecode Decompiler then I'll be adding a couple more bytecode decompilers inside of it as well.
