### ISSUE TITLE
More Shit

### ISSUE THREAD

**Issue by Konloch** [Konloch/bytecode-viewer#98]
Need to do code revert and manually add the changes back into BCV. Someone broke something.
    - Opening a single class file
    - Using arrow keys for navigation
    - Two classes with same internal name in two jars will not open
    - Allatori string decryption is non-functioning
    - GUI hanging? - Need to look into this

Another bug I ran into was rsyntaxpane failing to display a class file. The work around for this is a toggle for syntax highlighting (which probably should have been a setting in the first place).

Just going to update this as I find more bugs.

**Comment by samczsun** [comment]
Two classes with the same internal name in two jars will not open

**Comment by Konloch** [comment]
Yeah Allatori string decryption isn't working on my end also.

Theres a shutdown hook to kill the processes, so if you're killing java via task manager it won't call on the shutdown hook to kill the other processes.

As for maven, BCV downstreams the libraries on first boot from github, I assume I could apply the same technique using maven, but I really don't have the time to overhaul everything. (Hardly have time to fix small bugs these days.)

Thanks for the report about the internal name, I'll fix that asap. Should be an easy fix.

**Comment by samczsun** [comment]
I'm interested in maintaining this project on the side if you're open to help.

As for Maven, I notice you've manually shaded in Apache Commons, ASM, isoparser, and imgscalr. These could be handled by Maven resulting in a much cleaner project.

**Comment by Konloch** [comment]
Do you have Skype? If so add kalenkinloch.

If not email me at konloch@gmail.com, let's talk there.

**Comment by Szperak** [comment]
Allatori string decrypter is working for some specific classes, I think that it's unnecessary and can be removed. 
https://github.com/Konloch/bytecode-viewer/commit/a0d552e573fdc65b8cd24c29371fd8e424e3abdc

In this commit for example I removed the class viewing code, because I've changed the code to load also class binary contents. (Without removing it classes were showing twice)
